//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictRandomStoryTypeEnum : int
{
    /// <summary>
    /// 散财事件
    /// </summary>
    give_coin = 0,
    /// <summary>
    /// 打架除妖
    /// </summary>
    help_kill_enemy = 1,
    /// <summary>
    /// 灵石助人
    /// </summary>
    give_ruby = 2,
    /// <summary>
    /// 捐献物资
    /// </summary>
    give_good = 3,
    /// <summary>
    /// 损失钱财
    /// </summary>
    lost_coin = 4,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 5,

}

public class DictRandomStoryTypeEnumString
{
    /// <summary>
    /// 散财事件
    /// </summary>
    public const string give_coin = "give_coin";
    /// <summary>
    /// 打架除妖
    /// </summary>
    public const string help_kill_enemy = "help_kill_enemy";
    /// <summary>
    /// 灵石助人
    /// </summary>
    public const string give_ruby = "give_ruby";
    /// <summary>
    /// 捐献物资
    /// </summary>
    public const string give_good = "give_good";
    /// <summary>
    /// 损失钱财
    /// </summary>
    public const string lost_coin = "lost_coin";

public static string[] vlas = new string[]{
		
"give_coin",

"help_kill_enemy",

"give_ruby",

"give_good",

"lost_coin",
""
	};
}
