//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictRechargeTypeEnum : int
{
    /// <summary>
    /// 一般
    /// </summary>
    normal = 0,
    /// <summary>
    /// 每日礼包
    /// </summary>
    daygift = 1,
    /// <summary>
    /// 每周礼包
    /// </summary>
    weekgift = 2,
    /// <summary>
    /// 新号限时礼包
    /// </summary>
    tmgift = 3,
    /// <summary>
    /// 等级礼包
    /// </summary>
    levelgift = 4,
    /// <summary>
    /// 等级限时礼包
    /// </summary>
    leveltmgift = 5,
    /// <summary>
    /// 一般持续购买礼包
    /// </summary>
    chixulibao = 6,
    /// <summary>
    /// 月卡
    /// </summary>
    yueka = 7,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 8,

}

public class DictRechargeTypeEnumString
{
    /// <summary>
    /// 一般
    /// </summary>
    public const string normal = "normal";
    /// <summary>
    /// 每日礼包
    /// </summary>
    public const string daygift = "daygift";
    /// <summary>
    /// 每周礼包
    /// </summary>
    public const string weekgift = "weekgift";
    /// <summary>
    /// 新号限时礼包
    /// </summary>
    public const string tmgift = "tmgift";
    /// <summary>
    /// 等级礼包
    /// </summary>
    public const string levelgift = "levelgift";
    /// <summary>
    /// 等级限时礼包
    /// </summary>
    public const string leveltmgift = "leveltmgift";
    /// <summary>
    /// 一般持续购买礼包
    /// </summary>
    public const string chixulibao = "chixulibao";
    /// <summary>
    /// 月卡
    /// </summary>
    public const string yueka = "yueka";

public static string[] vlas = new string[]{
		
"normal",

"daygift",

"weekgift",

"tmgift",

"levelgift",

"leveltmgift",

"chixulibao",

"yueka",
""
	};
}
