//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictHeroExportPropEnum : int
{
    /// <summary>
    /// 伤害
    /// </summary>
    DMG = 1,
    /// <summary>
    /// 治疗
    /// </summary>
    hp = 2,
    /// <summary>
    /// 防御
    /// </summary>
    DEF = 3,
    /// <summary>
    /// 攻击
    /// </summary>
    ATK = 4,
    /// <summary>
    /// 身法
    /// </summary>
    shenfa = 5,
    /// <summary>
    /// 内力
    /// </summary>
    neili = 6,
    /// <summary>
    /// 闪避
    /// </summary>
    shanbi = 7,
    /// <summary>
    /// 禁锢
    /// </summary>
    jingzhi = 8,
    /// <summary>
    /// 血量上限
    /// </summary>
    hp_max = 9,
    /// <summary>
    /// 血量百分比上限
    /// </summary>
    hp_max_percent = 10,
    /// <summary>
    /// 暴击率
    /// </summary>
    crit_radio = 11,
    /// <summary>
    /// 暴击伤害
    /// </summary>
    crit_damage_percent = 12,
    /// <summary>
    /// 眩晕
    /// </summary>
    Xuanyun = 13,
    /// <summary>
    /// 昏睡
    /// </summary>
    HunShui = 14,
    /// <summary>
    /// 封印，不能回复魔法血量
    /// </summary>
    Fengyin = 15,
    /// <summary>
    /// 魅惑
    /// </summary>
    Meihuo = 16,
    /// <summary>
    /// 禁法
    /// </summary>
    JinFa = 17,
    /// <summary>
    /// 虚弱，防御伤害降低
    /// </summary>
    XuRuo = 18,
    /// <summary>
    /// 禁锢抗性
    /// </summary>
    unjingu = 19,
    /// <summary>
    /// 眩晕抗性
    /// </summary>
    unXuanyun = 20,
    /// <summary>
    /// 昏睡抗性
    /// </summary>
    unHunshui = 21,
    /// <summary>
    /// 虚弱抗性
    /// </summary>
    unXuruo = 22,
    /// <summary>
    /// 魅惑抗性
    /// </summary>
    unMeihuo = 23,
    /// <summary>
    /// 禁法抗性
    /// </summary>
    unJinfa = 24,
    /// <summary>
    /// 封印抗性
    /// </summary>
    unFengyin = 25,
    /// <summary>
    /// 吸血
    /// </summary>
    XIXUE = 26,
    /// <summary>
    /// 闪避
    /// </summary>
    MISS = 27,
    /// <summary>
    /// 隐身
    /// </summary>
    CLOAKING = 28,
    /// <summary>
    /// 忍术标记
    /// </summary>
    RENSHUBIAOJI = 29,
    /// <summary>
    /// 攻速
    /// </summary>
    ATK_SPEED = 30,
    /// <summary>
    /// 吸血率
    /// </summary>
    XIXUE_Factor = 31,
    /// <summary>
    /// 免疫
    /// </summary>
    immune = 32,
    /// <summary>
    /// 攻击属性
    /// </summary>
    atk_shuxing = 33,
    /// <summary>
    /// 沉默
    /// </summary>
    chengmo = 34,
    /// <summary>
    /// 增伤率
    /// </summary>
    dmg_add_per = 35,
    /// <summary>
    /// 减伤率
    /// </summary>
    dmg_des_per = 36,
    /// <summary>
    /// 筋骨
    /// </summary>
    jingu = 37,
    /// <summary>
    /// 伤害反弹
    /// </summary>
    dmg_fantan = 38,
    /// <summary>
    /// 嘲讽
    /// </summary>
    chaofeng = 39,
    /// <summary>
    /// 对前排隐身
    /// </summary>
    dui_qianpai_yinshen = 40,
    /// <summary>
    /// 对后排隐身
    /// </summary>
    dui_houpai_yinshen = 41,
    /// <summary>
    /// 治疗增加百分比
    /// </summary>
    treat_per = 42,
    /// <summary>
    /// 抗爆率
    /// </summary>
    kang_crit_per = 43,
    /// <summary>
    /// 抗爆伤害衰减
    /// </summary>
    kang_crit_dmg_per = 44,
    /// <summary>
    /// 免疫Buff
    /// </summary>
    mianyi_buff = 45,
    /// <summary>
    /// 免死
    /// </summary>
    mianyi_dead = 46,
    /// <summary>
    /// 抗吸血
    /// </summary>
    kang_xixue = 47,
    /// <summary>
    /// 命中
    /// </summary>
    mingzhong = 48,
    /// <summary>
    /// 破防
    /// </summary>
    pofang = 49,
    /// <summary>
    /// 抵抗
    /// </summary>
    buff_immune = 50,
    /// <summary>
    /// 忽视闪避
    /// </summary>
    attack_no_miss = 51,
    /// <summary>
    /// 忽视命中
    /// </summary>
    behit_no_mingzhong = 52,
    /// <summary>
    /// 反弹系数
    /// </summary>
    fantan_factor = 53,
    
    /// <summary>
    /// 移动速度
    /// </summary>
    move_speed = 54,
    
    /// <summary>
    /// 魔法
    /// </summary>
    mp = 55,
    
    /// <summary>
    /// 怒气
    /// </summary>
    angle = 56,
    
    /// <summary>
    /// 耐力
    /// </summary>
    naili = 57,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT ,

}

public class DictHeroExportPropEnumString
{
    /// <summary>
    /// 伤害
    /// </summary>
    public const string DMG = "DMG";
    /// <summary>
    /// 治疗
    /// </summary>
    public const string hp = "hp";
    /// <summary>
    /// 防御
    /// </summary>
    public const string DEF = "DEF";
    /// <summary>
    /// 攻击
    /// </summary>
    public const string ATK = "ATK";
    /// <summary>
    /// 身法
    /// </summary>
    public const string shenfa = "shenfa";
    /// <summary>
    /// 内力
    /// </summary>
    public const string neili = "neili";
    /// <summary>
    /// 闪避
    /// </summary>
    public const string shanbi = "shanbi";
    /// <summary>
    /// 禁锢
    /// </summary>
    public const string jingzhi = "jingzhi";
    /// <summary>
    /// 血量上限
    /// </summary>
    public const string hp_max = "hp_max";
    /// <summary>
    /// 血量百分比上限
    /// </summary>
    public const string hp_max_percent = "hp_max_percent";
    /// <summary>
    /// 暴击率
    /// </summary>
    public const string crit_radio = "crit_radio";
    /// <summary>
    /// 暴击伤害
    /// </summary>
    public const string crit_damage_percent = "crit_damage_percent";
    /// <summary>
    /// 眩晕
    /// </summary>
    public const string Xuanyun = "Xuanyun";
    /// <summary>
    /// 昏睡
    /// </summary>
    public const string HunShui = "HunShui";
    /// <summary>
    /// 封印，不能回复魔法血量
    /// </summary>
    public const string Fengyin = "Fengyin";
    /// <summary>
    /// 魅惑
    /// </summary>
    public const string Meihuo = "Meihuo";
    /// <summary>
    /// 禁法
    /// </summary>
    public const string JinFa = "JinFa";
    /// <summary>
    /// 虚弱，防御伤害降低
    /// </summary>
    public const string XuRuo = "XuRuo";
    /// <summary>
    /// 禁锢抗性
    /// </summary>
    public const string unjingu = "unjingu";
    /// <summary>
    /// 眩晕抗性
    /// </summary>
    public const string unXuanyun = "unXuanyun";
    /// <summary>
    /// 昏睡抗性
    /// </summary>
    public const string unHunshui = "unHunshui";
    /// <summary>
    /// 虚弱抗性
    /// </summary>
    public const string unXuruo = "unXuruo";
    /// <summary>
    /// 魅惑抗性
    /// </summary>
    public const string unMeihuo = "unMeihuo";
    /// <summary>
    /// 禁法抗性
    /// </summary>
    public const string unJinfa = "unJinfa";
    /// <summary>
    /// 封印抗性
    /// </summary>
    public const string unFengyin = "unFengyin";
    /// <summary>
    /// 吸血
    /// </summary>
    public const string XIXUE = "XIXUE";
    /// <summary>
    /// 闪避
    /// </summary>
    public const string MISS = "MISS";
    /// <summary>
    /// 隐身
    /// </summary>
    public const string CLOAKING = "CLOAKING";
    /// <summary>
    /// 忍术标记
    /// </summary>
    public const string RENSHUBIAOJI = "RENSHUBIAOJI";
    /// <summary>
    /// 攻速
    /// </summary>
    public const string ATK_SPEED = "ATK_SPEED";
    /// <summary>
    /// 吸血率
    /// </summary>
    public const string XIXUE_Factor = "XIXUE_Factor";
    /// <summary>
    /// 免疫
    /// </summary>
    public const string immune = "immune";
    /// <summary>
    /// 攻击属性
    /// </summary>
    public const string atk_shuxing = "atk_shuxing";
    /// <summary>
    /// 沉默
    /// </summary>
    public const string chengmo = "chengmo";
    /// <summary>
    /// 增伤率
    /// </summary>
    public const string dmg_add_per = "dmg_add_per";
    /// <summary>
    /// 减伤率
    /// </summary>
    public const string dmg_des_per = "dmg_des_per";
    /// <summary>
    /// 筋骨
    /// </summary>
    public const string jingu = "jingu";
    /// <summary>
    /// 伤害反弹
    /// </summary>
    public const string dmg_fantan = "dmg_fantan";
    /// <summary>
    /// 嘲讽
    /// </summary>
    public const string chaofeng = "chaofeng";
    /// <summary>
    /// 对前排隐身
    /// </summary>
    public const string dui_qianpai_yinshen = "dui_qianpai_yinshen";
    /// <summary>
    /// 对后排隐身
    /// </summary>
    public const string dui_houpai_yinshen = "dui_houpai_yinshen";
    /// <summary>
    /// 治疗增加百分比
    /// </summary>
    public const string treat_per = "treat_per";
    /// <summary>
    /// 抗爆率
    /// </summary>
    public const string kang_crit_per = "kang_crit_per";
    /// <summary>
    /// 抗爆伤害衰减
    /// </summary>
    public const string kang_crit_dmg_per = "kang_crit_dmg_per";
    /// <summary>
    /// 免疫Buff
    /// </summary>
    public const string mianyi_buff = "mianyi_buff";
    /// <summary>
    /// 免死
    /// </summary>
    public const string mianyi_dead = "mianyi_dead";
    /// <summary>
    /// 抗吸血
    /// </summary>
    public const string kang_xixue = "kang_xixue";
    /// <summary>
    /// 命中
    /// </summary>
    public const string mingzhong = "mingzhong";
    /// <summary>
    /// 破防
    /// </summary>
    public const string pofang = "pofang";
    /// <summary>
    /// 抵抗
    /// </summary>
    public const string buff_immune = "buff_immune";
    /// <summary>
    /// 忽视闪避
    /// </summary>
    public const string attack_no_miss = "attack_no_miss";
    /// <summary>
    /// 忽视命中
    /// </summary>
    public const string behit_no_mingzhong = "behit_no_mingzhong";
    /// <summary>
    /// 反弹系数
    /// </summary>
    public const string fantan_factor = "fantan_factor";

public static string[] vlas = new string[]{
		
"DMG",

"hp",

"DEF",

"ATK",

"shenfa",

"neili",

"shanbi",

"jingzhi",

"hp_max",

"hp_max_percent",

"crit_radio",

"crit_damage_percent",

"Xuanyun",

"HunShui",

"Fengyin",

"Meihuo",

"JinFa",

"XuRuo",

"unjingu",

"unXuanyun",

"unHunshui",

"unXuruo",

"unMeihuo",

"unJinfa",

"unFengyin",

"XIXUE",

"MISS",

"CLOAKING",

"RENSHUBIAOJI",

"ATK_SPEED",

"XIXUE_Factor",

"immune",

"atk_shuxing",

"chengmo",

"dmg_add_per",

"dmg_des_per",

"jingu",

"dmg_fantan",

"chaofeng",

"dui_qianpai_yinshen",

"dui_houpai_yinshen",

"treat_per",

"kang_crit_per",

"kang_crit_dmg_per",

"mianyi_buff",

"mianyi_dead",

"kang_xixue",

"mingzhong",

"pofang",

"buff_immune",

"attack_no_miss",

"behit_no_mingzhong",

"fantan_factor",
""
	};
}
