//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictMenpaiMenpaiDataEnum : int
{
    /// <summary>
    /// 江湖
    /// </summary>
    jianghu = 0,
    /// <summary>
    /// 御剑门
    /// </summary>
    fahun = 1,
    /// <summary>
    /// 六扇门
    /// </summary>
    guimen = 2,
    /// <summary>
    /// 巧木枋
    /// </summary>
    qingxin = 3,
    /// <summary>
    /// 清心阁
    /// </summary>
    shaolin = 4,
    /// <summary>
    /// 少林寺
    /// </summary>
    taixu = 5,
    /// <summary>
    /// 太虚们
    /// </summary>
    yujian = 6,
    /// <summary>
    /// 月刀门
    /// </summary>
    yuedao = 7,
    /// <summary>
    /// 法魂门
    /// </summary>
    chaoting = 8,
    /// <summary>
    /// 鬼门
    /// </summary>
    qiaomufang = 9,
    /// <summary>
    /// 折梅剑阁
    /// </summary>
    zhemeijiange = 10,
    /// <summary>
    /// 凌霄殿
    /// </summary>
    donghuanjianpai = 11,
    /// <summary>
    /// 聚宝阁
    /// </summary>
    tiandaozong = 12,
    /// <summary>
    /// 龙啸谷
    /// </summary>
    guigu = 13,
    /// <summary>
    /// 天机阁
    /// </summary>
    guyuemen = 14,
    /// <summary>
    /// 天道宗
    /// </summary>
    fahuasi = 15,
    /// <summary>
    /// 天雷院
    /// </summary>
    shushanpai = 16,
    /// <summary>
    /// 血魔宗
    /// </summary>
    piaomiaoge = 17,
    /// <summary>
    /// 万佛宗
    /// </summary>
    yaowangzong = 18,
    /// <summary>
    /// 逍遥派
    /// </summary>
    xuanyuanmen = 19,
    /// <summary>
    /// 血杀楼
    /// </summary>
    kunlunpai = 20,
    /// <summary>
    /// 北斗星宫
    /// </summary>
    shuangxiumen = 21,
    /// <summary>
    /// 黄泉魔宗
    /// </summary>
    qionghuapai = 22,
    /// <summary>
    /// 药王谷
    /// </summary>
    paiyuejiao = 23,
    /// <summary>
    /// 真仙阁
    /// </summary>
    chunyangogng = 24,
    /// <summary>
    /// 云霄剑派
    /// </summary>
    erengu = 25,
    /// <summary>
    /// 玄天剑派
    /// </summary>
    qingyunmen = 26,
    /// <summary>
    /// 御灵宗
    /// </summary>
    butianjiao = 27,
    /// <summary>
    /// 百花门
    /// </summary>
    tianyahaige = 28,
    /// <summary>
    /// 尸傀宗
    /// </summary>
    jubaoge = 29,
    /// <summary>
    /// 万妖门
    /// </summary>
    dadaozong = 30,
    /// <summary>
    /// 鬼谷
    /// </summary>
    qingmuge = 31,
    /// <summary>
    /// 云梦剑派
    /// </summary>
    donghailonggong = 32,
    /// <summary>
    /// 冰镜宫
    /// </summary>
    gumogong = 33,
    /// <summary>
    /// 古魔宫
    /// </summary>
    jiujiaomen = 34,
    /// <summary>
    /// 烈焰宗
    /// </summary>
    hongliange = 35,
    /// <summary>
    /// 红莲岛
    /// </summary>
    liudaozong = 36,
    /// <summary>
    /// 青云门
    /// </summary>
    yunmengjianpai = 37,
    /// <summary>
    /// 留仙洞
    /// </summary>
    huangquanzong = 38,
    /// <summary>
    /// 东海龙宫
    /// </summary>
    qiaomufangmizong = 39,
    /// <summary>
    /// 幽冥宗
    /// </summary>
    zhemeijiangemizong = 40,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 41,

}

public class DictMenpaiMenpaiDataEnumString
{
    /// <summary>
    /// 江湖
    /// </summary>
    public const string jianghu = "jianghu";
    /// <summary>
    /// 御剑门
    /// </summary>
    public const string fahun = "fahun";
    /// <summary>
    /// 六扇门
    /// </summary>
    public const string guimen = "guimen";
    /// <summary>
    /// 巧木枋
    /// </summary>
    public const string qingxin = "qingxin";
    /// <summary>
    /// 清心阁
    /// </summary>
    public const string shaolin = "shaolin";
    /// <summary>
    /// 少林寺
    /// </summary>
    public const string taixu = "taixu";
    /// <summary>
    /// 太虚们
    /// </summary>
    public const string yujian = "yujian";
    /// <summary>
    /// 月刀门
    /// </summary>
    public const string yuedao = "yuedao";
    /// <summary>
    /// 法魂门
    /// </summary>
    public const string chaoting = "chaoting";
    /// <summary>
    /// 鬼门
    /// </summary>
    public const string qiaomufang = "qiaomufang";
    /// <summary>
    /// 折梅剑阁
    /// </summary>
    public const string zhemeijiange = "zhemeijiange";
    /// <summary>
    /// 凌霄殿
    /// </summary>
    public const string donghuanjianpai = "donghuanjianpai";
    /// <summary>
    /// 聚宝阁
    /// </summary>
    public const string tiandaozong = "tiandaozong";
    /// <summary>
    /// 龙啸谷
    /// </summary>
    public const string guigu = "guigu";
    /// <summary>
    /// 天机阁
    /// </summary>
    public const string guyuemen = "guyuemen";
    /// <summary>
    /// 天道宗
    /// </summary>
    public const string fahuasi = "fahuasi";
    /// <summary>
    /// 天雷院
    /// </summary>
    public const string shushanpai = "shushanpai";
    /// <summary>
    /// 血魔宗
    /// </summary>
    public const string piaomiaoge = "piaomiaoge";
    /// <summary>
    /// 万佛宗
    /// </summary>
    public const string yaowangzong = "yaowangzong";
    /// <summary>
    /// 逍遥派
    /// </summary>
    public const string xuanyuanmen = "xuanyuanmen";
    /// <summary>
    /// 血杀楼
    /// </summary>
    public const string kunlunpai = "kunlunpai";
    /// <summary>
    /// 北斗星宫
    /// </summary>
    public const string shuangxiumen = "shuangxiumen";
    /// <summary>
    /// 黄泉魔宗
    /// </summary>
    public const string qionghuapai = "qionghuapai";
    /// <summary>
    /// 药王谷
    /// </summary>
    public const string paiyuejiao = "paiyuejiao";
    /// <summary>
    /// 真仙阁
    /// </summary>
    public const string chunyangogng = "chunyangogng";
    /// <summary>
    /// 云霄剑派
    /// </summary>
    public const string erengu = "erengu";
    /// <summary>
    /// 玄天剑派
    /// </summary>
    public const string qingyunmen = "qingyunmen";
    /// <summary>
    /// 御灵宗
    /// </summary>
    public const string butianjiao = "butianjiao";
    /// <summary>
    /// 百花门
    /// </summary>
    public const string tianyahaige = "tianyahaige";
    /// <summary>
    /// 尸傀宗
    /// </summary>
    public const string jubaoge = "jubaoge";
    /// <summary>
    /// 万妖门
    /// </summary>
    public const string dadaozong = "dadaozong";
    /// <summary>
    /// 鬼谷
    /// </summary>
    public const string qingmuge = "qingmuge";
    /// <summary>
    /// 云梦剑派
    /// </summary>
    public const string donghailonggong = "donghailonggong";
    /// <summary>
    /// 冰镜宫
    /// </summary>
    public const string gumogong = "gumogong";
    /// <summary>
    /// 古魔宫
    /// </summary>
    public const string jiujiaomen = "jiujiaomen";
    /// <summary>
    /// 烈焰宗
    /// </summary>
    public const string hongliange = "hongliange";
    /// <summary>
    /// 红莲岛
    /// </summary>
    public const string liudaozong = "liudaozong";
    /// <summary>
    /// 青云门
    /// </summary>
    public const string yunmengjianpai = "yunmengjianpai";
    /// <summary>
    /// 留仙洞
    /// </summary>
    public const string huangquanzong = "huangquanzong";
    /// <summary>
    /// 东海龙宫
    /// </summary>
    public const string qiaomufangmizong = "qiaomufangmizong";
    /// <summary>
    /// 幽冥宗
    /// </summary>
    public const string zhemeijiangemizong = "zhemeijiangemizong";

public static string[] vlas = new string[]{
		
"jianghu",

"fahun",

"guimen",

"qingxin",

"shaolin",

"taixu",

"yujian",

"yuedao",

"chaoting",

"qiaomufang",

"zhemeijiange",

"donghuanjianpai",

"tiandaozong",

"guigu",

"guyuemen",

"fahuasi",

"shushanpai",

"piaomiaoge",

"yaowangzong",

"xuanyuanmen",

"kunlunpai",

"shuangxiumen",

"qionghuapai",

"paiyuejiao",

"chunyangogng",

"erengu",

"qingyunmen",

"butianjiao",

"tianyahaige",

"jubaoge",

"dadaozong",

"qingmuge",

"donghailonggong",

"gumogong",

"jiujiaomen",

"hongliange",

"liudaozong",

"yunmengjianpai",

"huangquanzong",

"qiaomufangmizong",

"zhemeijiangemizong",
""
	};
}
