//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictEquipEquipFromEnum : int
{
    /// <summary>
    /// 主线副本
    /// </summary>
    copy = 0,
    /// <summary>
    /// 天缘BOSS碎片合成
    /// </summary>
    compound = 1,
    /// <summary>
    /// 天缘BOSS掉落
    /// </summary>
    build = 2,
    /// <summary>
    /// 装备强化
    /// </summary>
    advance = 3,
    /// <summary>
    /// 练气打造
    /// </summary>
    equip_val = 4,
    /// <summary>
    /// 杂货铺商店
    /// </summary>
    zahuopu_shop = 5,
    /// <summary>
    /// 装备精华商店
    /// </summary>
    equip_val_shop = 6,
    /// <summary>
    /// 巧木枋制作
    /// </summary>
    qiaomufang = 7,
    /// <summary>
    /// 古代试炼
    /// </summary>
    gudaishilian = 8,
    /// <summary>
    /// 氪金
    /// </summary>
    rmb = 9,
    /// <summary>
    /// 竞技商店
    /// </summary>
    pvp = 10,
    /// <summary>
    /// 虚空商店
    /// </summary>
    xukong = 11,
    /// <summary>
    /// 掌门宝库
    /// </summary>
    zhangmenbaoku = 12,
    /// <summary>
    /// 稀有商店
    /// </summary>
    xiyou_shop = 13,
    /// <summary>
    /// 天机之争
    /// </summary>
    tianji = 14,
    /// <summary>
    /// 世界首领
    /// </summary>
    shijieboss = 15,
    /// <summary>
    /// 五人鸿蒙秘境
    /// </summary>
    mijing_hongmeng = 16,
    /// <summary>
    /// 五人混沌秘境
    /// </summary>
    mijing_hundun = 17,
    /// <summary>
    /// 五人无极秘境
    /// </summary>
    mijing_wuji = 18,
    /// <summary>
    /// 机缘
    /// </summary>
    iyuan = 19,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 20,

}

public class DictEquipEquipFromEnumString
{
    /// <summary>
    /// 主线副本
    /// </summary>
    public const string copy = "copy";
    /// <summary>
    /// 天缘BOSS碎片合成
    /// </summary>
    public const string compound = "compound";
    /// <summary>
    /// 天缘BOSS掉落
    /// </summary>
    public const string build = "build";
    /// <summary>
    /// 装备强化
    /// </summary>
    public const string advance = "advance";
    /// <summary>
    /// 练气打造
    /// </summary>
    public const string equip_val = "equip_val";
    /// <summary>
    /// 杂货铺商店
    /// </summary>
    public const string zahuopu_shop = "zahuopu_shop";
    /// <summary>
    /// 装备精华商店
    /// </summary>
    public const string equip_val_shop = "equip_val_shop";
    /// <summary>
    /// 巧木枋制作
    /// </summary>
    public const string qiaomufang = "qiaomufang";
    /// <summary>
    /// 古代试炼
    /// </summary>
    public const string gudaishilian = "gudaishilian";
    /// <summary>
    /// 氪金
    /// </summary>
    public const string rmb = "rmb";
    /// <summary>
    /// 竞技商店
    /// </summary>
    public const string pvp = "pvp";
    /// <summary>
    /// 虚空商店
    /// </summary>
    public const string xukong = "xukong";
    /// <summary>
    /// 掌门宝库
    /// </summary>
    public const string zhangmenbaoku = "zhangmenbaoku";
    /// <summary>
    /// 稀有商店
    /// </summary>
    public const string xiyou_shop = "xiyou_shop";
    /// <summary>
    /// 天机之争
    /// </summary>
    public const string tianji = "tianji";
    /// <summary>
    /// 世界首领
    /// </summary>
    public const string shijieboss = "shijieboss";
    /// <summary>
    /// 五人鸿蒙秘境
    /// </summary>
    public const string mijing_hongmeng = "mijing_hongmeng";
    /// <summary>
    /// 五人混沌秘境
    /// </summary>
    public const string mijing_hundun = "mijing_hundun";
    /// <summary>
    /// 五人无极秘境
    /// </summary>
    public const string mijing_wuji = "mijing_wuji";
    /// <summary>
    /// 机缘
    /// </summary>
    public const string iyuan = "iyuan";

public static string[] vlas = new string[]{
		
"copy",

"compound",

"build",

"advance",

"equip_val",

"zahuopu_shop",

"equip_val_shop",

"qiaomufang",

"gudaishilian",

"rmb",

"pvp",

"xukong",

"zhangmenbaoku",

"xiyou_shop",

"tianji",

"shijieboss",

"mijing_hongmeng",

"mijing_hundun",

"mijing_wuji",

"iyuan",
""
	};
}
