//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictHeroHeroClassEnum : int
{
    /// <summary>
    /// 小怪
    /// </summary>
    monster = 0,
    /// <summary>
    /// 后宫英雄
    /// </summary>
    girl = 1,
    /// <summary>
    /// 英雄
    /// </summary>
    hero = 2,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 3,

}

public class DictHeroHeroClassEnumString
{
    /// <summary>
    /// 小怪
    /// </summary>
    public const string monster = "monster";
    /// <summary>
    /// 后宫英雄
    /// </summary>
    public const string girl = "girl";
    /// <summary>
    /// 英雄
    /// </summary>
    public const string hero = "hero";

public static string[] vlas = new string[]{
		
"monster",

"girl",

"hero",
""
	};
}
