//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictHeroHeroTypeEnum : int
{
    /// <summary>
    /// 筋骨
    /// </summary>
    jingu = 1,
    /// <summary>
    /// 身法
    /// </summary>
    shenfa = 2,
    /// <summary>
    /// 内力
    /// </summary>
    neili = 3,
    /// <summary>
    /// 全能型
    /// </summary>
    daddy = 4,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 5,

}

public class DictHeroHeroTypeEnumString
{
    /// <summary>
    /// 筋骨
    /// </summary>
    public const string jingu = "jingu";
    /// <summary>
    /// 身法
    /// </summary>
    public const string shenfa = "shenfa";
    /// <summary>
    /// 内力
    /// </summary>
    public const string neili = "neili";
    /// <summary>
    /// 全能型
    /// </summary>
    public const string daddy = "daddy";

public static string[] vlas = new string[]{
		
"jingu",

"shenfa",

"neili",

"daddy",
""
	};
}
