//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictGoodTypeEnum : int
{
    /// <summary>
    /// 道具
    /// </summary>
    daoju = 0,
    /// <summary>
    /// 宝箱
    /// </summary>
    baoxiang = 1,
    /// <summary>
    /// 任务
    /// </summary>
    renwu = 2,
    /// <summary>
    /// 制作卷
    /// </summary>
    zhizuojuan = 3,
    /// <summary>
    /// 碎片
    /// </summary>
    suipian = 4,
    /// <summary>
    /// 药水
    /// </summary>
    yaoshui = 5,
    /// <summary>
    /// 花卉
    /// </summary>
    flower = 6,
    /// <summary>
    /// 装备碎片
    /// </summary>
    equip_suipian = 7,
    /// <summary>
    /// 姑娘碎片
    /// </summary>
    girl_suipian = 8,
    /// <summary>
    /// 主角药水
    /// </summary>
    zhujiao_yaoshui = 9,
    /// <summary>
    /// 洞府书籍
    /// </summary>
    dongfu_shuji = 10,
    /// <summary>
    /// 宝石
    /// </summary>
    baoshi = 11,
    /// <summary>
    /// 多选一宝箱
    /// </summary>
    baoxiang_select = 12,
    /// <summary>
    /// 许愿石
    /// </summary>
    xuyuanshi = 13,
    /// <summary>
    /// 五彩石
    /// </summary>
    wucaishi = 14,
    /// <summary>
    /// 多倍药水
    /// </summary>
    jiasu_exp = 15,
    /// <summary>
    /// 五彩药水
    /// </summary>
    wucai_yaoshui = 16,
    /// <summary>
    /// 抽卡卷
    /// </summary>
    chouka_juan = 17,
    /// <summary>
    /// 随机宝箱
    /// </summary>
    baoxiang_random = 18,
    /// <summary>
    /// 矿石
    /// </summary>
    kuangshi = 19,
    /// <summary>
    /// 修士尸体
    /// </summary>
    xiushi_shiti = 20,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 21,

}

public class DictGoodTypeEnumString
{
    /// <summary>
    /// 道具
    /// </summary>
    public const string daoju = "daoju";
    /// <summary>
    /// 宝箱
    /// </summary>
    public const string baoxiang = "baoxiang";
    /// <summary>
    /// 任务
    /// </summary>
    public const string renwu = "renwu";
    /// <summary>
    /// 制作卷
    /// </summary>
    public const string zhizuojuan = "zhizuojuan";
    /// <summary>
    /// 碎片
    /// </summary>
    public const string suipian = "suipian";
    /// <summary>
    /// 药水
    /// </summary>
    public const string yaoshui = "yaoshui";
    /// <summary>
    /// 花卉
    /// </summary>
    public const string flower = "flower";
    /// <summary>
    /// 装备碎片
    /// </summary>
    public const string equip_suipian = "equip_suipian";
    /// <summary>
    /// 姑娘碎片
    /// </summary>
    public const string girl_suipian = "girl_suipian";
    /// <summary>
    /// 主角药水
    /// </summary>
    public const string zhujiao_yaoshui = "zhujiao_yaoshui";
    /// <summary>
    /// 洞府书籍
    /// </summary>
    public const string dongfu_shuji = "dongfu_shuji";
    /// <summary>
    /// 宝石
    /// </summary>
    public const string baoshi = "baoshi";
    /// <summary>
    /// 多选一宝箱
    /// </summary>
    public const string baoxiang_select = "baoxiang_select";
    /// <summary>
    /// 许愿石
    /// </summary>
    public const string xuyuanshi = "xuyuanshi";
    /// <summary>
    /// 五彩石
    /// </summary>
    public const string wucaishi = "wucaishi";
    /// <summary>
    /// 多倍药水
    /// </summary>
    public const string jiasu_exp = "jiasu_exp";
    /// <summary>
    /// 五彩药水
    /// </summary>
    public const string wucai_yaoshui = "wucai_yaoshui";
    /// <summary>
    /// 抽卡卷
    /// </summary>
    public const string chouka_juan = "chouka_juan";
    /// <summary>
    /// 随机宝箱
    /// </summary>
    public const string baoxiang_random = "baoxiang_random";
    /// <summary>
    /// 矿石
    /// </summary>
    public const string kuangshi = "kuangshi";
    /// <summary>
    /// 修士尸体
    /// </summary>
    public const string xiushi_shiti = "xiushi_shiti";

public static string[] vlas = new string[]{
		
"daoju",

"baoxiang",

"renwu",

"zhizuojuan",

"suipian",

"yaoshui",

"flower",

"equip_suipian",

"girl_suipian",

"zhujiao_yaoshui",

"dongfu_shuji",

"baoshi",

"baoxiang_select",

"xuyuanshi",

"wucaishi",

"jiasu_exp",

"wucai_yaoshui",

"chouka_juan",

"baoxiang_random",

"kuangshi",

"xiushi_shiti",
""
	};
}
