//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictChapterTypeEnum : int
{
    /// <summary>
    /// 普通刷本
    /// </summary>
    normal = 0,
    /// <summary>
    /// 天缘副本
    /// </summary>
    tianyuan = 1,
    /// <summary>
    /// 铜钱试炼
    /// </summary>
    coin_feiqi = 2,
    /// <summary>
    /// 经验试炼
    /// </summary>
    exp_feiqi = 3,
    /// <summary>
    /// 灵石试炼
    /// </summary>
    ruby_feiqi = 4,
    /// <summary>
    /// 仙缘试炼
    /// </summary>
    flower_feiqi = 5,
    /// <summary>
    /// 英雄传记
    /// </summary>
    hero_collection = 6,
    /// <summary>
    /// 掠夺校服
    /// </summary>
    school_harry = 7,
    /// <summary>
    /// 掠夺坐骑
    /// </summary>
    ride_harry = 8,
    /// <summary>
    /// 红尘绮梦
    /// </summary>
    girl_collection = 9,
    /// <summary>
    /// 一般爬塔
    /// </summary>
    normal_pata = 10,
    /// <summary>
    /// 一般关卡
    /// </summary>
    normal_battle = 11,
    /// <summary>
    /// 世界boss
    /// </summary>
    world_boss = 12,
    /// <summary>
    /// 天机之争
    /// </summary>
    tianji_boss = 13,
    /// <summary>
    /// 试炼
    /// </summary>
    shilian = 14,
    /// <summary>
    /// 切磋
    /// </summary>
    qiecuo = 15,
    /// <summary>
    /// 竞技场
    /// </summary>
    pvp = 16,
    /// <summary>
    /// 门派boss
    /// </summary>
    menpai_boss = 17,
    /// <summary>
    /// 跨服boss
    /// </summary>
    kuafu_boss = 18,
    /// <summary>
    /// 活动本
    /// </summary>
    huodong = 19,
    /// <summary>
    /// 组队本
    /// </summary>
    team_copy = 20,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 21,

}

public class DictChapterTypeEnumString
{
    /// <summary>
    /// 普通刷本
    /// </summary>
    public const string normal = "normal";
    /// <summary>
    /// 天缘副本
    /// </summary>
    public const string tianyuan = "tianyuan";
    /// <summary>
    /// 铜钱试炼
    /// </summary>
    public const string coin_feiqi = "coin_feiqi";
    /// <summary>
    /// 经验试炼
    /// </summary>
    public const string exp_feiqi = "exp_feiqi";
    /// <summary>
    /// 灵石试炼
    /// </summary>
    public const string ruby_feiqi = "ruby_feiqi";
    /// <summary>
    /// 仙缘试炼
    /// </summary>
    public const string flower_feiqi = "flower_feiqi";
    /// <summary>
    /// 英雄传记
    /// </summary>
    public const string hero_collection = "hero_collection";
    /// <summary>
    /// 掠夺校服
    /// </summary>
    public const string school_harry = "school_harry";
    /// <summary>
    /// 掠夺坐骑
    /// </summary>
    public const string ride_harry = "ride_harry";
    /// <summary>
    /// 红尘绮梦
    /// </summary>
    public const string girl_collection = "girl_collection";
    /// <summary>
    /// 一般爬塔
    /// </summary>
    public const string normal_pata = "normal_pata";
    /// <summary>
    /// 一般关卡
    /// </summary>
    public const string normal_battle = "normal_battle";
    /// <summary>
    /// 世界boss
    /// </summary>
    public const string world_boss = "world_boss";
    /// <summary>
    /// 天机之争
    /// </summary>
    public const string tianji_boss = "tianji_boss";
    /// <summary>
    /// 试炼
    /// </summary>
    public const string shilian = "shilian";
    /// <summary>
    /// 切磋
    /// </summary>
    public const string qiecuo = "qiecuo";
    /// <summary>
    /// 竞技场
    /// </summary>
    public const string pvp = "pvp";
    /// <summary>
    /// 门派boss
    /// </summary>
    public const string menpai_boss = "menpai_boss";
    /// <summary>
    /// 跨服boss
    /// </summary>
    public const string kuafu_boss = "kuafu_boss";
    /// <summary>
    /// 活动本
    /// </summary>
    public const string huodong = "huodong";
    /// <summary>
    /// 组队本
    /// </summary>
    public const string team_copy = "team_copy";

public static string[] vlas = new string[]{
		
"normal",

"tianyuan",

"coin_feiqi",

"exp_feiqi",

"ruby_feiqi",

"flower_feiqi",

"hero_collection",

"school_harry",

"ride_harry",

"girl_collection",

"normal_pata",

"normal_battle",

"world_boss",

"tianji_boss",

"shilian",

"qiecuo",

"pvp",

"menpai_boss",

"kuafu_boss",

"huodong",

"team_copy",
""
	};
}
