//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictGoodCompoundTypeEnum : int
{
    /// <summary>
    /// 研究所
    /// </summary>
    yanjiusuo = 0,
    /// <summary>
    /// 药水配方
    /// </summary>
    yaoshuipeifang = 1,
    /// <summary>
    /// 蘑菇
    /// </summary>
    mogu = 2,
    /// <summary>
    /// 五彩石
    /// </summary>
    wucai = 3,
    /// <summary>
    /// 分身合成
    /// </summary>
    fenshen = 4,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 5,

}

public class DictGoodCompoundTypeEnumString
{
    /// <summary>
    /// 研究所
    /// </summary>
    public const string yanjiusuo = "yanjiusuo";
    /// <summary>
    /// 药水配方
    /// </summary>
    public const string yaoshuipeifang = "yaoshuipeifang";
    /// <summary>
    /// 蘑菇
    /// </summary>
    public const string mogu = "mogu";
    /// <summary>
    /// 五彩石
    /// </summary>
    public const string wucai = "wucai";
    /// <summary>
    /// 分身合成
    /// </summary>
    public const string fenshen = "fenshen";

public static string[] vlas = new string[]{
		
"yanjiusuo",

"yaoshuipeifang",

"mogu",

"wucai",

"fenshen",
""
	};
}
