//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictPlayerDongfuCanwuTypeEnum : int
{
    /// <summary>
    /// 打坐
    /// </summary>
    dazuo = 1,
    /// <summary>
    /// 聚灵
    /// </summary>
    juling = 2,
    /// <summary>
    /// 抚琴
    /// </summary>
    fuqin = 3,
    /// <summary>
    /// 炼丹
    /// </summary>
    liandan = 4,
    /// <summary>
    /// 吟诗
    /// </summary>
    yinshi = 5,
    /// <summary>
    /// 凝神
    /// </summary>
    zazhi = 6,
    /// <summary>
    /// 参悟
    /// </summary>
    menpaiskill = 7,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 8,

}

public class DictPlayerDongfuCanwuTypeEnumString
{
    /// <summary>
    /// 打坐
    /// </summary>
    public const string dazuo = "dazuo";
    /// <summary>
    /// 聚灵
    /// </summary>
    public const string juling = "juling";
    /// <summary>
    /// 抚琴
    /// </summary>
    public const string fuqin = "fuqin";
    /// <summary>
    /// 炼丹
    /// </summary>
    public const string liandan = "liandan";
    /// <summary>
    /// 吟诗
    /// </summary>
    public const string yinshi = "yinshi";
    /// <summary>
    /// 凝神
    /// </summary>
    public const string zazhi = "zazhi";
    /// <summary>
    /// 参悟
    /// </summary>
    public const string menpaiskill = "menpaiskill";

public static string[] vlas = new string[]{
		
"dazuo",

"juling",

"fuqin",

"liandan",

"yinshi",

"zazhi",

"menpaiskill",
""
	};
}
