//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public delegate void DictVoid_LoadFinishedCallBack();
public delegate void DictString_LoadFinishedCallBack(string filePath);

public partial class DictDataManager
{
    private static DictDataManager m_instance;
    private string m_dataPath;
    private int m_initCount = 0;
    private bool m_isInit = false;

    //
    private DictVoid_LoadFinishedCallBack m_loadFinishedCallBack;

    public static DictDataManager Instance
    {
        get
        {
            if(m_instance == null)
            {
                m_instance = new DictDataManager();
            }

            return m_instance;
        }
    }

    public static void Release()
    {
        m_instance = null;
    }

    public void Init(string path,DictVoid_LoadFinishedCallBack callBack)
    {
      m_loadFinishedCallBack = callBack;

      //
      if(m_isInit)
      {
        if(m_loadFinishedCallBack != null)
        {
          m_loadFinishedCallBack();
        }
    return;
      }

      //
      m_dataPath = path;

        dictExample.Load(m_dataPath,OnLoadFinished);

        dictChapterTeamPataGroup.Load(m_dataPath,OnLoadFinished);

        dictChapterPataDiff.Load(m_dataPath,OnLoadFinished);

        dictChapterPataGroup.Load(m_dataPath,OnLoadFinished);

        dictChapterChapter.Load(m_dataPath,OnLoadFinished);

        dictChapterScene.Load(m_dataPath,OnLoadFinished);

        dictChapterCopy.Load(m_dataPath,OnLoadFinished);

        dictChapterEnemy.Load(m_dataPath,OnLoadFinished);

        dictChapterCopyDrop.Load(m_dataPath,OnLoadFinished);

        dictSceneEle.Load(m_dataPath,OnLoadFinished);

        dictKuafuboss.Load(m_dataPath,OnLoadFinished);

        dictKuafubossRankReward.Load(m_dataPath,OnLoadFinished);

        dictKuafubossDamageReward.Load(m_dataPath,OnLoadFinished);

        dictMenpaiboss.Load(m_dataPath,OnLoadFinished);

        dictMenpaibossRankReward.Load(m_dataPath,OnLoadFinished);

        dictMenpaibossDamageReward.Load(m_dataPath,OnLoadFinished);

        dictRenwuMain.Load(m_dataPath,OnLoadFinished);

        dictRenwuStory.Load(m_dataPath,OnLoadFinished);

        dictRenwuSub.Load(m_dataPath,OnLoadFinished);

        dictRenwuSubDetail.Load(m_dataPath,OnLoadFinished);

        dictRandomStory.Load(m_dataPath,OnLoadFinished);

        dictChapterActivity.Load(m_dataPath,OnLoadFinished);

        dictChapterActivityTotalZhaomuReward.Load(m_dataPath,OnLoadFinished);

        dictChapterActivityDamageReward.Load(m_dataPath,OnLoadFinished);

        dictChapterActivityCountReward.Load(m_dataPath,OnLoadFinished);

        dictChapterActivityChapter.Load(m_dataPath,OnLoadFinished);

        dictRewardTask.Load(m_dataPath,OnLoadFinished);

        dictReward.Load(m_dataPath,OnLoadFinished);

        dictRewardSign.Load(m_dataPath,OnLoadFinished);

        dictRewardPvp.Load(m_dataPath,OnLoadFinished);

        dictEquipEquip.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipQulity.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipAbility.Load(m_dataPath,OnLoadFinished);

        dictEquipWeaponType.Load(m_dataPath,OnLoadFinished);

        dictEquipSuitEquipAblity.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipSkill.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipLevel.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipStar.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipCbaCost.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipTModel.Load(m_dataPath,OnLoadFinished);

        dictEquipEquipAdvance.Load(m_dataPath,OnLoadFinished);

        dictPlayerProp.Load(m_dataPath,OnLoadFinished);

        dictPlayerChongsheng.Load(m_dataPath,OnLoadFinished);

        dictPlayerSelectHeroAttribute.Load(m_dataPath,OnLoadFinished);

        dictPlayerSelectHeroImage.Load(m_dataPath,OnLoadFinished);

        dictPlayerSelectHeroJiyuan.Load(m_dataPath,OnLoadFinished);

        dictPlayerShuangxiu.Load(m_dataPath,OnLoadFinished);

        dictPlayerChenghao.Load(m_dataPath,OnLoadFinished);

        dictPlayerXiayiLevel.Load(m_dataPath,OnLoadFinished);

        dictPlayerXiuweiLev.Load(m_dataPath,OnLoadFinished);

        dictPlayerLevel.Load(m_dataPath,OnLoadFinished);

        dictPlayerYueliLevel.Load(m_dataPath,OnLoadFinished);

        dictPlayerDongfuCanwu.Load(m_dataPath,OnLoadFinished);

        dictPlayerDongfuCanwuType.Load(m_dataPath,OnLoadFinished);

        dictPlayerFenshen.Load(m_dataPath,OnLoadFinished);

        dictPlayerFenshenLev.Load(m_dataPath,OnLoadFinished);

        dictGoodEquipCompound.Load(m_dataPath,OnLoadFinished);

        dictGood.Load(m_dataPath,OnLoadFinished);

        dictGoodCompound.Load(m_dataPath,OnLoadFinished);

        dictGoodCompoundItem.Load(m_dataPath,OnLoadFinished);

        dictGoodWucaiPeifang.Load(m_dataPath,OnLoadFinished);

        dictGoodWucaiBaoshiAbility.Load(m_dataPath,OnLoadFinished);

        dictGoodBaoxiang.Load(m_dataPath,OnLoadFinished);

        dictGoodType.Load(m_dataPath,OnLoadFinished);

        dictRecharge.Load(m_dataPath,OnLoadFinished);

        dictRechargeType.Load(m_dataPath,OnLoadFinished);

        dictRechargeBuyCoin.Load(m_dataPath,OnLoadFinished);

        dictRechargeVip.Load(m_dataPath,OnLoadFinished);

        dictRechargeDateGift.Load(m_dataPath,OnLoadFinished);

        dictRechargeContinueLogin.Load(m_dataPath,OnLoadFinished);

        dictRechargeContinueLoginGift.Load(m_dataPath,OnLoadFinished);

        dictPopStory.Load(m_dataPath,OnLoadFinished);

        dictProduceMining.Load(m_dataPath,OnLoadFinished);

        dictZhaomuZhaomuDropType.Load(m_dataPath,OnLoadFinished);

        dictZhaomuZhaomuDropItem.Load(m_dataPath,OnLoadFinished);

        dictZhaomuZhaomuDropGood.Load(m_dataPath,OnLoadFinished);

        dictZhaomuZhaomuMustDrop.Load(m_dataPath,OnLoadFinished);

        dictDongfuHeroSq.Load(m_dataPath,OnLoadFinished);

        dictDongfuBuild.Load(m_dataPath,OnLoadFinished);

        dictDongfuBuildLev.Load(m_dataPath,OnLoadFinished);

        dictDongfuBuildProduce.Load(m_dataPath,OnLoadFinished);

        dictAbility.Load(m_dataPath,OnLoadFinished);

        dictMenpaiMenpaiData.Load(m_dataPath,OnLoadFinished);

        dictMenpaiMenpaiDiweiData.Load(m_dataPath,OnLoadFinished);

        dictMenpaiMenpaiZhuanzhiTask.Load(m_dataPath,OnLoadFinished);

        dictMenpaiMenpaiShiwu.Load(m_dataPath,OnLoadFinished);

        dictMenpaiMenpaiCheckData.Load(m_dataPath,OnLoadFinished);

        dictShopType.Load(m_dataPath,OnLoadFinished);

        dictShopTypeFreshCost.Load(m_dataPath,OnLoadFinished);

        dictShopNormal.Load(m_dataPath,OnLoadFinished);

        dictSystemLanguage.Load(m_dataPath,OnLoadFinished);

        dictSystemVersionRecord.Load(m_dataPath,OnLoadFinished);

        dictSystemCheatApp.Load(m_dataPath,OnLoadFinished);

        dictSystemModule.Load(m_dataPath,OnLoadFinished);

        dictSystemQuestion.Load(m_dataPath,OnLoadFinished);

        dictSystemConfig.Load(m_dataPath,OnLoadFinished);

        dictSystemQulity.Load(m_dataPath,OnLoadFinished);

        dictSystemUiAutoLoad.Load(m_dataPath,OnLoadFinished);

        dictSystemRollTip.Load(m_dataPath,OnLoadFinished);

        dictSystemPushMessage.Load(m_dataPath,OnLoadFinished);

        dictSystemGetItemFrom.Load(m_dataPath,OnLoadFinished);

        dictSystemFriendGift.Load(m_dataPath,OnLoadFinished);

        dictSystemAdsGift.Load(m_dataPath,OnLoadFinished);

        dictGuideUnit.Load(m_dataPath,OnLoadFinished);

        dictGuideStep.Load(m_dataPath,OnLoadFinished);

        dictGuideCondition.Load(m_dataPath,OnLoadFinished);

        dictNameFamily.Load(m_dataPath,OnLoadFinished);

        dictNameLast.Load(m_dataPath,OnLoadFinished);

        dictHeroHero.Load(m_dataPath,OnLoadFinished);

        dictHeroHeroXinlai.Load(m_dataPath,OnLoadFinished);

        dictHeroRelation.Load(m_dataPath,OnLoadFinished);

        dictHeroRelationType.Load(m_dataPath,OnLoadFinished);

        dictHeroHeroSay.Load(m_dataPath,OnLoadFinished);

        dictHeroHeroLev.Load(m_dataPath,OnLoadFinished);

        dictHeroHeroStar.Load(m_dataPath,OnLoadFinished);

        dictHeroHeroStarAddAbility.Load(m_dataPath,OnLoadFinished);

        dictHeroHeroType.Load(m_dataPath,OnLoadFinished);

        dictHeroStarAbility.Load(m_dataPath,OnLoadFinished);

        dictHeroSkillCalculate.Load(m_dataPath,OnLoadFinished);

        dictHeroZhuansheng.Load(m_dataPath,OnLoadFinished);

        dictHeroXilianUp.Load(m_dataPath,OnLoadFinished);

        dictHeroPasstiveSkill.Load(m_dataPath,OnLoadFinished);

        dictHeroSkillEffect.Load(m_dataPath,OnLoadFinished);

        dictHeroSkill.Load(m_dataPath,OnLoadFinished);

        dictHeroBuff.Load(m_dataPath,OnLoadFinished);

        dictHeroBuffProp.Load(m_dataPath,OnLoadFinished);

        dictHeroExportProp.Load(m_dataPath,OnLoadFinished);

        dictHeroAtkShuxingType.Load(m_dataPath,OnLoadFinished);

        dictHeroSkillReleaseSelect.Load(m_dataPath,OnLoadFinished);

        dictHeroSkillLev.Load(m_dataPath,OnLoadFinished);

        dictHeroZhaomuDropHero.Load(m_dataPath,OnLoadFinished);

        dictHeroZhaomuDropGood.Load(m_dataPath,OnLoadFinished);

      //
      DictPreLoadCache.PreLoadCache();
      m_isInit = true;
    }

    //
    private void OnLoadFinished(string filePath)
    {
        m_initCount--;

        if(m_initCount == 0)
        {
            // 表加载完毕
            if(m_loadFinishedCallBack != null)
            {
                m_loadFinishedCallBack();
            }
        }
    }


    public DictExample dictExample = new DictExample();

    public DictChapterTeamPataGroup dictChapterTeamPataGroup = new DictChapterTeamPataGroup();

    public DictChapterPataDiff dictChapterPataDiff = new DictChapterPataDiff();

    public DictChapterPataGroup dictChapterPataGroup = new DictChapterPataGroup();

    public DictChapterChapter dictChapterChapter = new DictChapterChapter();

    public DictChapterScene dictChapterScene = new DictChapterScene();

    public DictChapterCopy dictChapterCopy = new DictChapterCopy();

    public DictChapterEnemy dictChapterEnemy = new DictChapterEnemy();

    public DictChapterCopyDrop dictChapterCopyDrop = new DictChapterCopyDrop();

    public DictSceneEle dictSceneEle = new DictSceneEle();

    public DictKuafuboss dictKuafuboss = new DictKuafuboss();

    public DictKuafubossRankReward dictKuafubossRankReward = new DictKuafubossRankReward();

    public DictKuafubossDamageReward dictKuafubossDamageReward = new DictKuafubossDamageReward();

    public DictMenpaiboss dictMenpaiboss = new DictMenpaiboss();

    public DictMenpaibossRankReward dictMenpaibossRankReward = new DictMenpaibossRankReward();

    public DictMenpaibossDamageReward dictMenpaibossDamageReward = new DictMenpaibossDamageReward();

    public DictRenwuMain dictRenwuMain = new DictRenwuMain();

    public DictRenwuStory dictRenwuStory = new DictRenwuStory();

    public DictRenwuSub dictRenwuSub = new DictRenwuSub();

    public DictRenwuSubDetail dictRenwuSubDetail = new DictRenwuSubDetail();

    public DictRandomStory dictRandomStory = new DictRandomStory();

    public DictChapterActivity dictChapterActivity = new DictChapterActivity();

    public DictChapterActivityTotalZhaomuReward dictChapterActivityTotalZhaomuReward = new DictChapterActivityTotalZhaomuReward();

    public DictChapterActivityDamageReward dictChapterActivityDamageReward = new DictChapterActivityDamageReward();

    public DictChapterActivityCountReward dictChapterActivityCountReward = new DictChapterActivityCountReward();

    public DictChapterActivityChapter dictChapterActivityChapter = new DictChapterActivityChapter();

    public DictRewardTask dictRewardTask = new DictRewardTask();

    public DictReward dictReward = new DictReward();

    public DictRewardSign dictRewardSign = new DictRewardSign();

    public DictRewardPvp dictRewardPvp = new DictRewardPvp();

    public DictEquipEquip dictEquipEquip = new DictEquipEquip();

    public DictEquipEquipQulity dictEquipEquipQulity = new DictEquipEquipQulity();

    public DictEquipEquipAbility dictEquipEquipAbility = new DictEquipEquipAbility();

    public DictEquipWeaponType dictEquipWeaponType = new DictEquipWeaponType();

    public DictEquipSuitEquipAblity dictEquipSuitEquipAblity = new DictEquipSuitEquipAblity();

    public DictEquipEquipSkill dictEquipEquipSkill = new DictEquipEquipSkill();

    public DictEquipEquipLevel dictEquipEquipLevel = new DictEquipEquipLevel();

    public DictEquipEquipStar dictEquipEquipStar = new DictEquipEquipStar();

    public DictEquipEquipCbaCost dictEquipEquipCbaCost = new DictEquipEquipCbaCost();

    public DictEquipEquipTModel dictEquipEquipTModel = new DictEquipEquipTModel();

    public DictEquipEquipAdvance dictEquipEquipAdvance = new DictEquipEquipAdvance();

    public DictPlayerProp dictPlayerProp = new DictPlayerProp();

    public DictPlayerChongsheng dictPlayerChongsheng = new DictPlayerChongsheng();

    public DictPlayerSelectHeroAttribute dictPlayerSelectHeroAttribute = new DictPlayerSelectHeroAttribute();

    public DictPlayerSelectHeroImage dictPlayerSelectHeroImage = new DictPlayerSelectHeroImage();

    public DictPlayerSelectHeroJiyuan dictPlayerSelectHeroJiyuan = new DictPlayerSelectHeroJiyuan();

    public DictPlayerShuangxiu dictPlayerShuangxiu = new DictPlayerShuangxiu();

    public DictPlayerChenghao dictPlayerChenghao = new DictPlayerChenghao();

    public DictPlayerXiayiLevel dictPlayerXiayiLevel = new DictPlayerXiayiLevel();

    public DictPlayerXiuweiLev dictPlayerXiuweiLev = new DictPlayerXiuweiLev();

    public DictPlayerLevel dictPlayerLevel = new DictPlayerLevel();

    public DictPlayerYueliLevel dictPlayerYueliLevel = new DictPlayerYueliLevel();

    public DictPlayerDongfuCanwu dictPlayerDongfuCanwu = new DictPlayerDongfuCanwu();

    public DictPlayerDongfuCanwuType dictPlayerDongfuCanwuType = new DictPlayerDongfuCanwuType();

    public DictPlayerFenshen dictPlayerFenshen = new DictPlayerFenshen();

    public DictPlayerFenshenLev dictPlayerFenshenLev = new DictPlayerFenshenLev();

    public DictGoodEquipCompound dictGoodEquipCompound = new DictGoodEquipCompound();

    public DictGood dictGood = new DictGood();

    public DictGoodCompound dictGoodCompound = new DictGoodCompound();

    public DictGoodCompoundItem dictGoodCompoundItem = new DictGoodCompoundItem();

    public DictGoodWucaiPeifang dictGoodWucaiPeifang = new DictGoodWucaiPeifang();

    public DictGoodWucaiBaoshiAbility dictGoodWucaiBaoshiAbility = new DictGoodWucaiBaoshiAbility();

    public DictGoodBaoxiang dictGoodBaoxiang = new DictGoodBaoxiang();

    public DictGoodType dictGoodType = new DictGoodType();

    public DictRecharge dictRecharge = new DictRecharge();

    public DictRechargeType dictRechargeType = new DictRechargeType();

    public DictRechargeBuyCoin dictRechargeBuyCoin = new DictRechargeBuyCoin();

    public DictRechargeVip dictRechargeVip = new DictRechargeVip();

    public DictRechargeDateGift dictRechargeDateGift = new DictRechargeDateGift();

    public DictRechargeContinueLogin dictRechargeContinueLogin = new DictRechargeContinueLogin();

    public DictRechargeContinueLoginGift dictRechargeContinueLoginGift = new DictRechargeContinueLoginGift();

    public DictPopStory dictPopStory = new DictPopStory();

    public DictProduceMining dictProduceMining = new DictProduceMining();

    public DictZhaomuZhaomuDropType dictZhaomuZhaomuDropType = new DictZhaomuZhaomuDropType();

    public DictZhaomuZhaomuDropItem dictZhaomuZhaomuDropItem = new DictZhaomuZhaomuDropItem();

    public DictZhaomuZhaomuDropGood dictZhaomuZhaomuDropGood = new DictZhaomuZhaomuDropGood();

    public DictZhaomuZhaomuMustDrop dictZhaomuZhaomuMustDrop = new DictZhaomuZhaomuMustDrop();

    public DictDongfuHeroSq dictDongfuHeroSq = new DictDongfuHeroSq();

    public DictDongfuBuild dictDongfuBuild = new DictDongfuBuild();

    public DictDongfuBuildLev dictDongfuBuildLev = new DictDongfuBuildLev();

    public DictDongfuBuildProduce dictDongfuBuildProduce = new DictDongfuBuildProduce();

    public DictAbility dictAbility = new DictAbility();

    public DictMenpaiMenpaiData dictMenpaiMenpaiData = new DictMenpaiMenpaiData();

    public DictMenpaiMenpaiDiweiData dictMenpaiMenpaiDiweiData = new DictMenpaiMenpaiDiweiData();

    public DictMenpaiMenpaiZhuanzhiTask dictMenpaiMenpaiZhuanzhiTask = new DictMenpaiMenpaiZhuanzhiTask();

    public DictMenpaiMenpaiShiwu dictMenpaiMenpaiShiwu = new DictMenpaiMenpaiShiwu();

    public DictMenpaiMenpaiCheckData dictMenpaiMenpaiCheckData = new DictMenpaiMenpaiCheckData();

    public DictShopType dictShopType = new DictShopType();

    public DictShopTypeFreshCost dictShopTypeFreshCost = new DictShopTypeFreshCost();

    public DictShopNormal dictShopNormal = new DictShopNormal();

    public DictSystemLanguage dictSystemLanguage = new DictSystemLanguage();

    public DictSystemVersionRecord dictSystemVersionRecord = new DictSystemVersionRecord();

    public DictSystemCheatApp dictSystemCheatApp = new DictSystemCheatApp();

    public DictSystemModule dictSystemModule = new DictSystemModule();

    public DictSystemQuestion dictSystemQuestion = new DictSystemQuestion();

    public DictSystemConfig dictSystemConfig = new DictSystemConfig();

    public DictSystemQulity dictSystemQulity = new DictSystemQulity();

    public DictSystemUiAutoLoad dictSystemUiAutoLoad = new DictSystemUiAutoLoad();

    public DictSystemRollTip dictSystemRollTip = new DictSystemRollTip();

    public DictSystemPushMessage dictSystemPushMessage = new DictSystemPushMessage();

    public DictSystemGetItemFrom dictSystemGetItemFrom = new DictSystemGetItemFrom();

    public DictSystemFriendGift dictSystemFriendGift = new DictSystemFriendGift();

    public DictSystemAdsGift dictSystemAdsGift = new DictSystemAdsGift();

    public DictGuideUnit dictGuideUnit = new DictGuideUnit();

    public DictGuideStep dictGuideStep = new DictGuideStep();

    public DictGuideCondition dictGuideCondition = new DictGuideCondition();

    public DictNameFamily dictNameFamily = new DictNameFamily();

    public DictNameLast dictNameLast = new DictNameLast();

    public DictHeroHero dictHeroHero = new DictHeroHero();

    public DictHeroHeroXinlai dictHeroHeroXinlai = new DictHeroHeroXinlai();

    public DictHeroRelation dictHeroRelation = new DictHeroRelation();

    public DictHeroRelationType dictHeroRelationType = new DictHeroRelationType();

    public DictHeroHeroSay dictHeroHeroSay = new DictHeroHeroSay();

    public DictHeroHeroLev dictHeroHeroLev = new DictHeroHeroLev();

    public DictHeroHeroStar dictHeroHeroStar = new DictHeroHeroStar();

    public DictHeroHeroStarAddAbility dictHeroHeroStarAddAbility = new DictHeroHeroStarAddAbility();

    public DictHeroHeroType dictHeroHeroType = new DictHeroHeroType();

    public DictHeroStarAbility dictHeroStarAbility = new DictHeroStarAbility();

    public DictHeroSkillCalculate dictHeroSkillCalculate = new DictHeroSkillCalculate();

    public DictHeroZhuansheng dictHeroZhuansheng = new DictHeroZhuansheng();

    public DictHeroXilianUp dictHeroXilianUp = new DictHeroXilianUp();

    public DictHeroPasstiveSkill dictHeroPasstiveSkill = new DictHeroPasstiveSkill();

    public DictHeroSkillEffect dictHeroSkillEffect = new DictHeroSkillEffect();

    public DictHeroSkill dictHeroSkill = new DictHeroSkill();

    public DictHeroBuff dictHeroBuff = new DictHeroBuff();

    public DictHeroBuffProp dictHeroBuffProp = new DictHeroBuffProp();

    public DictHeroExportProp dictHeroExportProp = new DictHeroExportProp();

    public DictHeroAtkShuxingType dictHeroAtkShuxingType = new DictHeroAtkShuxingType();

    public DictHeroSkillReleaseSelect dictHeroSkillReleaseSelect = new DictHeroSkillReleaseSelect();

    public DictHeroSkillLev dictHeroSkillLev = new DictHeroSkillLev();

    public DictHeroZhaomuDropHero dictHeroZhaomuDropHero = new DictHeroZhaomuDropHero();

    public DictHeroZhaomuDropGood dictHeroZhaomuDropGood = new DictHeroZhaomuDropGood();

    //
    public static string[] s_allFileName = new string[]
    {

    "dict_example",

    "dict_chapter_team_pata_group",

    "dict_chapter_pata_diff",

    "dict_chapter_pata_group",

    "dict_chapter_chapter",

    "dict_chapter_scene",

    "dict_chapter_copy",

    "dict_chapter_enemy",

    "dict_chapter_copy_drop",

    "dict_scene_ele",

    "dict_kuafuboss",

    "dict_kuafuboss_rank_reward",

    "dict_kuafuboss_damage_reward",

    "dict_menpaiboss",

    "dict_menpaiboss_rank_reward",

    "dict_menpaiboss_damage_reward",

    "dict_renwu_main",

    "dict_renwu_story",

    "dict_renwu_sub",

    "dict_renwu_sub_detail",

    "dict_random_story",

    "dict_chapter_activity",

    "dict_chapter_activity_total_zhaomu_reward",

    "dict_chapter_activity_damage_reward",

    "dict_chapter_activity_count_reward",

    "dict_chapter_activity_chapter",

    "dict_reward_task",

    "dict_reward",

    "dict_reward_sign",

    "dict_reward_pvp",

    "dict_equip_equip",

    "dict_equip_equip_qulity",

    "dict_equip_equip_ability",

    "dict_equip_weapon_type",

    "dict_equip_suit_equip_ablity",

    "dict_equip_equip_skill",

    "dict_equip_equip_level",

    "dict_equip_equip_star",

    "dict_equip_equip_cba_cost",

    "dict_equip_equip_t_model",

    "dict_equip_equip_advance",

    "dict_player_prop",

    "dict_player_chongsheng",

    "dict_player_select_hero_attribute",

    "dict_player_select_hero_image",

    "dict_player_select_hero_jiyuan",

    "dict_player_shuangxiu",

    "dict_player_chenghao",

    "dict_player_xiayi_level",

    "dict_player_xiuwei_lev",

    "dict_player_level",

    "dict_player_yueli_level",

    "dict_player_dongfu_canwu",

    "dict_player_dongfu_canwu_type",

    "dict_player_fenshen",

    "dict_player_fenshen_lev",

    "dict_good_equip_compound",

    "dict_good",

    "dict_good_compound",

    "dict_good_compound_item",

    "dict_good_wucai_peifang",

    "dict_good_wucai_baoshi_ability",

    "dict_good_baoxiang",

    "dict_good_type",

    "dict_recharge",

    "dict_recharge_type",

    "dict_recharge_buy_coin",

    "dict_recharge_vip",

    "dict_recharge_date_gift",

    "dict_recharge_continue_login",

    "dict_recharge_continue_login_gift",

    "dict_pop_story",

    "dict_produce_mining",

    "dict_zhaomu_zhaomu_drop_type",

    "dict_zhaomu_zhaomu_drop_item",

    "dict_zhaomu_zhaomu_drop_good",

    "dict_zhaomu_zhaomu_must_drop",

    "dict_dongfu_hero_sq",

    "dict_dongfu_build",

    "dict_dongfu_build_lev",

    "dict_dongfu_build_produce",

    "dict_ability",

    "dict_menpai_menpai_data",

    "dict_menpai_menpai_diwei_data",

    "dict_menpai_menpai_zhuanzhi_task",

    "dict_menpai_menpai_shiwu",

    "dict_menpai_menpai_check_data",

    "dict_shop_type",

    "dict_shop_type_fresh_cost",

    "dict_shop_normal",

    "dict_system_language",

    "dict_system_version_record",

    "dict_system_cheat_app",

    "dict_system_module",

    "dict_system_question",

    "dict_system_config",

    "dict_system_qulity",

    "dict_system_ui_auto_load",

    "dict_system_roll_tip",

    "dict_system_push_message",

    "dict_system_get_item_from",

    "dict_system_friend_gift",

    "dict_system_ads_gift",

    "dict_guide_unit",

    "dict_guide_step",

    "dict_guide_condition",

    "dict_name_family",

    "dict_name_last",

    "dict_hero_hero",

    "dict_hero_hero_xinlai",

    "dict_hero_relation",

    "dict_hero_relation_type",

    "dict_hero_hero_say",

    "dict_hero_hero_lev",

    "dict_hero_hero_star",

    "dict_hero_hero_star_add_ability",

    "dict_hero_hero_type",

    "dict_hero_star_ability",

    "dict_hero_skill_calculate",

    "dict_hero_zhuansheng",

    "dict_hero_xilian_up",

    "dict_hero_passtive_skill",

    "dict_hero_skill_effect",

    "dict_hero_skill",

    "dict_hero_buff",

    "dict_hero_buff_prop",

    "dict_hero_export_prop",

    "dict_hero_atk_shuxing_type",

    "dict_hero_skill_release_select",

    "dict_hero_skill_lev",

    "dict_hero_zhaomu_drop_hero",

    "dict_hero_zhaomu_drop_good",

    };
}

