//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictShopNormal
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 主键ID
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 主键ID
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 商品classId
        /// </summary>
        public string class_id;
     /// <summary>
        /// 商品propId
        /// </summary>
        public string prop_id;
     /// <summary>
        /// 商品objId
        /// </summary>
        public string obj_id;
     /// <summary>
        /// 商品数量num
        /// </summary>
        public XorInt num_xor;
     /// <summary>
        /// 商品数量num
        /// </summary>
        public int num{
            get{
                return num_xor.val;
            }
        }
     /// <summary>
        /// 商品货币
        /// </summary>
        public string huobi;
     /// <summary>
        /// 商品售价
        /// </summary>
        public XorInt cost_xor;
     /// <summary>
        /// 商品售价
        /// </summary>
        public int cost{
            get{
                return cost_xor.val;
            }
        }
     /// <summary>
        /// 商店类型
        /// </summary>
        public XorInt shop_type_xor;
     /// <summary>
        /// 商店类型
        /// </summary>
        public int shop_type{
            get{
                return shop_type_xor.val;
            }
        }
     /// <summary>
        /// 商品限制
        /// </summary>
        public List<string> shop_limiteds;
     /// <summary>
        /// 库存
        /// </summary>
        public XorInt max_num_xor;
     /// <summary>
        /// 库存
        /// </summary>
        public int max_num{
            get{
                return max_num_xor.val;
            }
        }
     /// <summary>
        /// 商品单价
        /// </summary>
        public XorInt one_cost_xor;
     /// <summary>
        /// 商品单价
        /// </summary>
        public int one_cost{
            get{
                return one_cost_xor.val;
            }
        }

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictShopNormal m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_shop_normal.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.class_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["class_id"]]);
            model.prop_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["prop_id"]]);
            model.obj_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["obj_id"]]);
            model.num_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["num"]]),fileReader.randomUtil);
            model.huobi = DictTypeConvert.ParseString(str[fileReader.typeName2Index["huobi"]]);
            model.cost_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["cost"]]),fileReader.randomUtil);
            model.shop_type_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["shop_type"]]),fileReader.randomUtil);
            model.shop_limiteds = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["shop_limiteds"]]);
            model.max_num_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["max_num"]]),fileReader.randomUtil);
            model.one_cost_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["one_cost"]]),fileReader.randomUtil);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictShopNormal Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
