//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictHeroPasstiveSkill
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 技能id
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 技能id
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 名字
        /// </summary>
        public string name;
     /// <summary>
        /// 描述
        /// </summary>
        public string desc;
     /// <summary>
        /// 英雄ID
        /// </summary>
        public XorInt hero_int_id_xor;
     /// <summary>
        /// 英雄ID
        /// </summary>
        public int hero_int_id{
            get{
                return hero_int_id_xor.val;
            }
        }
     /// <summary>
        /// 英雄ID
        /// </summary>
        public string hero_id;
     /// <summary>
        /// 解锁星级
        /// </summary>
        public XorInt hero_star_xor;
     /// <summary>
        /// 解锁星级
        /// </summary>
        public int hero_star{
            get{
                return hero_star_xor.val;
            }
        }
     /// <summary>
        /// 洞府品质ID
        /// </summary>
        public XorInt dongfu_hero_sq_id_xor;
     /// <summary>
        /// 洞府品质ID
        /// </summary>
        public int dongfu_hero_sq_id{
            get{
                return dongfu_hero_sq_id_xor.val;
            }
        }
     /// <summary>
        /// df品质等级
        /// </summary>
        public XorInt dongfu_hero_sq_lev_xor;
     /// <summary>
        /// df品质等级
        /// </summary>
        public int dongfu_hero_sq_lev{
            get{
                return dongfu_hero_sq_lev_xor.val;
            }
        }
     /// <summary>
        /// 能力值
        /// </summary>
        public XorInt nengli_lev_xor;
     /// <summary>
        /// 能力值
        /// </summary>
        public int nengli_lev{
            get{
                return nengli_lev_xor.val;
            }
        }
     /// <summary>
        /// 能力
        /// </summary>
        public string abilityId;
     /// <summary>
        /// 能力加成系数
        /// </summary>
        public XorDouble ability_factor_xor;
     /// <summary>
        /// 能力加成系数
        /// </summary>
        public double ability_factor{
            get{
                return ability_factor_xor.val;
            }
        }

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictHeroPasstiveSkill m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_hero_passtive_skill.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["desc"]]);
            model.hero_int_id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["hero_int_id"]]),fileReader.randomUtil);
            model.hero_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["hero_id"]]);
            model.hero_star_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["hero_star"]]),fileReader.randomUtil);
            model.dongfu_hero_sq_id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["dongfu_hero_sq_id"]]),fileReader.randomUtil);
            model.dongfu_hero_sq_lev_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["dongfu_hero_sq_lev"]]),fileReader.randomUtil);
            model.nengli_lev_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["nengli_lev"]]),fileReader.randomUtil);
            model.abilityId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["abilityId"]]);
            model.ability_factor_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["ability_factor"]]),fileReader.randomUtil);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictHeroPasstiveSkill Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
