//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictGoodWucaiPeifang
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 主键
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 主键
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 合成物
        /// </summary>
        public string targetId;
     /// <summary>
        /// 需要物品类型
        /// </summary>
        public List<string> cost_goods;
     /// <summary>
        /// 矿物精华
        /// </summary>
        public XorInt cost_kuangwu_val_xor;
     /// <summary>
        /// 矿物精华
        /// </summary>
        public int cost_kuangwu_val{
            get{
                return cost_kuangwu_val_xor.val;
            }
        }
     /// <summary>
        /// 宝石精华
        /// </summary>
        public XorInt cost_baoshi_val_xor;
     /// <summary>
        /// 宝石精华
        /// </summary>
        public int cost_baoshi_val{
            get{
                return cost_baoshi_val_xor.val;
            }
        }
     /// <summary>
        /// 主体宝石
        /// </summary>
        public string baoshi_base_good_id;
     /// <summary>
        /// 特殊good_base_id
        /// </summary>
        public List<string> base_good_ids;
     /// <summary>
        /// 掉落其他物品
        /// </summary>
        public List<string> drop_reward_ids;
     /// <summary>
        /// 掉落其他物品概率
        /// </summary>
        public List<double> drop_radios;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictGoodWucaiPeifang m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_good_wucai_peifang.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.targetId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["targetId"]]);
            model.cost_goods = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["cost_goods"]]);
            model.cost_kuangwu_val_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["cost_kuangwu_val"]]),fileReader.randomUtil);
            model.cost_baoshi_val_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["cost_baoshi_val"]]),fileReader.randomUtil);
            model.baoshi_base_good_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["baoshi_base_good_id"]]);
            model.base_good_ids = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["base_good_ids"]]);
            model.drop_reward_ids = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["drop_reward_ids"]]);
            model.drop_radios = DictTypeConvert.ParseArrayDouble(str[fileReader.typeName2Index["drop_radios"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictGoodWucaiPeifang Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
