//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictMenpaiboss
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// bossId
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// bossId
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 开放时间
        /// </summary>
        public XorInt beginTime_xor;
     /// <summary>
        /// 开放时间
        /// </summary>
        public int beginTime{
            get{
                return beginTime_xor.val;
            }
        }
     /// <summary>
        /// 结束时间
        /// </summary>
        public XorInt endTime_xor;
     /// <summary>
        /// 结束时间
        /// </summary>
        public int endTime{
            get{
                return endTime_xor.val;
            }
        }
     /// <summary>
        /// 某场标记
        /// </summary>
        public XorInt boss_key_id_xor;
     /// <summary>
        /// 某场标记
        /// </summary>
        public int boss_key_id{
            get{
                return boss_key_id_xor.val;
            }
        }
     /// <summary>
        /// 日期标记
        /// </summary>
        public XorInt open_day_xor;
     /// <summary>
        /// 日期标记
        /// </summary>
        public int open_day{
            get{
                return open_day_xor.val;
            }
        }
     /// <summary>
        /// 副本ID
        /// </summary>
        public string copyId;
     /// <summary>
        /// 英雄ID
        /// </summary>
        public string heroId;
     /// <summary>
        /// 首名额外随机奖励
        /// </summary>
        public List<string> rewards;
     /// <summary>
        /// 随机掉落奖励
        /// </summary>
        public List<string> drop_random_rewards;
     /// <summary>
        /// 随机掉落概率
        /// </summary>
        public List<double> drop_random_radio;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictMenpaiboss m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_menpaiboss.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.beginTime_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["beginTime"]]),fileReader.randomUtil);
            model.endTime_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["endTime"]]),fileReader.randomUtil);
            model.boss_key_id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["boss_key_id"]]),fileReader.randomUtil);
            model.open_day_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["open_day"]]),fileReader.randomUtil);
            model.copyId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["copyId"]]);
            model.heroId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["heroId"]]);
            model.rewards = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["rewards"]]);
            model.drop_random_rewards = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["drop_random_rewards"]]);
            model.drop_random_radio = DictTypeConvert.ParseArrayDouble(str[fileReader.typeName2Index["drop_random_radio"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictMenpaiboss Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
