//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictEquipEquipAbility
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 装备ID
        /// </summary>
        public string id;
     /// <summary>
        /// 物品名称
        /// </summary>
        public string name;
     /// <summary>
        /// 效果描述
        /// </summary>
        public string desc;
     /// <summary>
        /// 生效条件
        /// </summary>
        public string active_taskid;
     /// <summary>
        /// 生效对象
        /// </summary>
        public string active_target;
     /// <summary>
        /// 百分比生效能力
        /// </summary>
        public string percent_ability;
     /// <summary>
        /// 数值生效能力
        /// </summary>
        public string shuzhi_ability;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<string, Model> m_dict;

    // Get The Dictionary
    public Dictionary<string, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(string id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictEquipEquipAbility m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_equip_equip_ability.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<string,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["id"]]);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["desc"]]);
            model.active_taskid = DictTypeConvert.ParseString(str[fileReader.typeName2Index["active_taskid"]]);
            model.active_target = DictTypeConvert.ParseString(str[fileReader.typeName2Index["active_target"]]);
            model.percent_ability = DictTypeConvert.ParseString(str[fileReader.typeName2Index["percent_ability"]]);
            model.shuzhi_ability = DictTypeConvert.ParseString(str[fileReader.typeName2Index["shuzhi_ability"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictEquipEquipAbility Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
