//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictMenpaiMenpaiShiwu
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// id
        /// </summary>
        public string id;
     /// <summary>
        /// name
        /// </summary>
        public string name;
     /// <summary>
        /// type
        /// </summary>
        public XorInt type_xor;
     /// <summary>
        /// type
        /// </summary>
        public int type{
            get{
                return type_xor.val;
            }
        }
     /// <summary>
        /// 产出
        /// </summary>
        public string classId;
     /// <summary>
        /// 产出
        /// </summary>
        public string porpId;
     /// <summary>
        /// 产出
        /// </summary>
        public string objId;
     /// <summary>
        /// num
        /// </summary>
        public XorInt num_xor;
     /// <summary>
        /// num
        /// </summary>
        public int num{
            get{
                return num_xor.val;
            }
        }
     /// <summary>
        /// descSpeed
        /// </summary>
        public string descSpeed;
     /// <summary>
        /// descUnit
        /// </summary>
        public string descUnit;
     /// <summary>
        /// descBtn
        /// </summary>
        public string descBtn;
     /// <summary>
        /// descGuaji
        /// </summary>
        public string descGuaji;
     /// <summary>
        /// word
        /// </summary>
        public string word;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<string, Model> m_dict;

    // Get The Dictionary
    public Dictionary<string, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(string id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictMenpaiMenpaiShiwu m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_menpai_menpai_shiwu.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<string,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["id"]]);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.type_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["type"]]),fileReader.randomUtil);
            model.classId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["classId"]]);
            model.porpId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["porpId"]]);
            model.objId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["objId"]]);
            model.num_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["num"]]),fileReader.randomUtil);
            model.descSpeed = DictTypeConvert.ParseString(str[fileReader.typeName2Index["descSpeed"]]);
            model.descUnit = DictTypeConvert.ParseString(str[fileReader.typeName2Index["descUnit"]]);
            model.descBtn = DictTypeConvert.ParseString(str[fileReader.typeName2Index["descBtn"]]);
            model.descGuaji = DictTypeConvert.ParseString(str[fileReader.typeName2Index["descGuaji"]]);
            model.word = DictTypeConvert.ParseString(str[fileReader.typeName2Index["word"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictMenpaiMenpaiShiwu Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
