//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictHeroSkillCalculate
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 技能id
        /// </summary>
        public string id;
     /// <summary>
        /// 公式
        /// </summary>
        public string gongshi;
     /// <summary>
        /// 公式次序
        /// </summary>
        public XorInt order_xor;
     /// <summary>
        /// 公式次序
        /// </summary>
        public int order{
            get{
                return order_xor.val;
            }
        }
     /// <summary>
        /// 左对象
        /// </summary>
        public string left_target;
     /// <summary>
        /// 左数
        /// </summary>
        public string left;
     /// <summary>
        /// 算子
        /// </summary>
        public string cal_operator;
     /// <summary>
        /// 右对象
        /// </summary>
        public string right_target;
     /// <summary>
        /// 右数
        /// </summary>
        public string right;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<string, Model> m_dict;

    // Get The Dictionary
    public Dictionary<string, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(string id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictHeroSkillCalculate m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_hero_skill_calculate.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<string,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["id"]]);
            model.gongshi = DictTypeConvert.ParseString(str[fileReader.typeName2Index["gongshi"]]);
            model.order_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["order"]]),fileReader.randomUtil);
            model.left_target = DictTypeConvert.ParseString(str[fileReader.typeName2Index["left_target"]]);
            model.left = DictTypeConvert.ParseString(str[fileReader.typeName2Index["left"]]);
            model.cal_operator = DictTypeConvert.ParseString(str[fileReader.typeName2Index["cal_operator"]]);
            model.right_target = DictTypeConvert.ParseString(str[fileReader.typeName2Index["right_target"]]);
            model.right = DictTypeConvert.ParseString(str[fileReader.typeName2Index["right"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictHeroSkillCalculate Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
