//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictMenpaiMenpaiDiweiData
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// lv
        /// </summary>
        public XorInt lv_xor;
     /// <summary>
        /// lv
        /// </summary>
        public int lv{
            get{
                return lv_xor.val;
            }
        }
     /// <summary>
        /// name
        /// </summary>
        public string name;
     /// <summary>
        /// 威望
        /// </summary>
        public XorInt weiwang_xor;
     /// <summary>
        /// 威望
        /// </summary>
        public int weiwang{
            get{
                return weiwang_xor.val;
            }
        }
     /// <summary>
        /// 任务ID
        /// </summary>
        public List<string> taskIDs;
     /// <summary>
        /// 福利RewardGroupId
        /// </summary>
        public List<string> fuli_rewards;
     /// <summary>
        /// 描述
        /// </summary>
        public string desc;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int lv)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictMenpaiMenpaiDiweiData m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(lv))
            {
                return m_dict[lv];
            }
            else
            {
                Debug.LogError ("error id:"+lv);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_menpai_menpai_diwei_data.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.lv_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["lv"]]),fileReader.randomUtil);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.weiwang_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["weiwang"]]),fileReader.randomUtil);
            model.taskIDs = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["taskIDs"]]);
            model.fuli_rewards = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["fuli_rewards"]]);
            model.desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["desc"]]);

            if (m_dict.ContainsKey(model.lv) == false)
            {
                m_dict.Add(model.lv, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictMenpaiMenpaiDiweiData Parse:Same Key = " + model.lv);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
