//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictChapterCopyDrop
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 主键id
        /// </summary>
        public string id;
     /// <summary>
        /// 关卡ID
        /// </summary>
        public string copy_id;
     /// <summary>
        /// 掉落装备
        /// </summary>
        public List<string> equip_id;
     /// <summary>
        /// 掉落装备概率
        /// </summary>
        public XorDouble drop_equip_radio_xor;
     /// <summary>
        /// 掉落装备概率
        /// </summary>
        public double drop_equip_radio{
            get{
                return drop_equip_radio_xor.val;
            }
        }
     /// <summary>
        /// 掉落物品
        /// </summary>
        public List<string> good_id;
     /// <summary>
        /// 掉落数量
        /// </summary>
        public XorInt good_num_xor;
     /// <summary>
        /// 掉落数量
        /// </summary>
        public int good_num{
            get{
                return good_num_xor.val;
            }
        }
     /// <summary>
        /// 掉落概率
        /// </summary>
        public XorDouble drop_good_radio_xor;
     /// <summary>
        /// 掉落概率
        /// </summary>
        public double drop_good_radio{
            get{
                return drop_good_radio_xor.val;
            }
        }

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<string, Model> m_dict;

    // Get The Dictionary
    public Dictionary<string, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(string id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictChapterCopyDrop m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_chapter_copy_drop.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<string,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["id"]]);
            model.copy_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["copy_id"]]);
            model.equip_id = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["equip_id"]]);
            model.drop_equip_radio_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["drop_equip_radio"]]),fileReader.randomUtil);
            model.good_id = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["good_id"]]);
            model.good_num_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["good_num"]]),fileReader.randomUtil);
            model.drop_good_radio_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["drop_good_radio"]]),fileReader.randomUtil);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictChapterCopyDrop Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
