//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictHeroZhuansheng
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 转生次数
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 转生次数
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 名字
        /// </summary>
        public string name;
     /// <summary>
        /// 转生限制等级
        /// </summary>
        public XorInt lev_limited_xor;
     /// <summary>
        /// 转生限制等级
        /// </summary>
        public int lev_limited{
            get{
                return lev_limited_xor.val;
            }
        }
     /// <summary>
        /// 转生星级上限
        /// </summary>
        public XorInt star_lev_limited_xor;
     /// <summary>
        /// 转生星级上限
        /// </summary>
        public int star_lev_limited{
            get{
                return star_lev_limited_xor.val;
            }
        }
     /// <summary>
        /// 洗练上限次数
        /// </summary>
        public XorInt xilian_limited_count_xor;
     /// <summary>
        /// 洗练上限次数
        /// </summary>
        public int xilian_limited_count{
            get{
                return xilian_limited_count_xor.val;
            }
        }
     /// <summary>
        /// 转生石类型
        /// </summary>
        public string good_id;
     /// <summary>
        /// 转生石数量
        /// </summary>
        public XorInt good_num_xor;
     /// <summary>
        /// 转生石数量
        /// </summary>
        public int good_num{
            get{
                return good_num_xor.val;
            }
        }
     /// <summary>
        /// 洗髓上限
        /// </summary>
        public XorInt max_xishui_xor;
     /// <summary>
        /// 洗髓上限
        /// </summary>
        public int max_xishui{
            get{
                return max_xishui_xor.val;
            }
        }
     /// <summary>
        /// 洗髓下限
        /// </summary>
        public XorInt min_xishui_xor;
     /// <summary>
        /// 洗髓下限
        /// </summary>
        public int min_xishui{
            get{
                return min_xishui_xor.val;
            }
        }

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictHeroZhuansheng m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_hero_zhuansheng.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.lev_limited_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["lev_limited"]]),fileReader.randomUtil);
            model.star_lev_limited_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["star_lev_limited"]]),fileReader.randomUtil);
            model.xilian_limited_count_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["xilian_limited_count"]]),fileReader.randomUtil);
            model.good_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["good_id"]]);
            model.good_num_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["good_num"]]),fileReader.randomUtil);
            model.max_xishui_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["max_xishui"]]),fileReader.randomUtil);
            model.min_xishui_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["min_xishui"]]),fileReader.randomUtil);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictHeroZhuansheng Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
