//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictZhaomuZhaomuDropType
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 招募类型id
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 招募类型id
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 名称
        /// </summary>
        public string name;
     /// <summary>
        /// 内部说明
        /// </summary>
        public string say;
     /// <summary>
        /// 招募图
        /// </summary>
        public string hero_icon;
     /// <summary>
        /// 招募描述
        /// </summary>
        public string detail;
     /// <summary>
        /// 招募公示
        /// </summary>
        public string gongshi;
     /// <summary>
        /// 单抽价格
        /// </summary>
        public string propId;
     /// <summary>
        /// 单抽价格
        /// </summary>
        public XorInt one_cost_xor;
     /// <summary>
        /// 单抽价格
        /// </summary>
        public int one_cost{
            get{
                return one_cost_xor.val;
            }
        }
     /// <summary>
        /// 十连抽价格
        /// </summary>
        public XorInt ten_cost_xor;
     /// <summary>
        /// 十连抽价格
        /// </summary>
        public int ten_cost{
            get{
                return ten_cost_xor.val;
            }
        }
     /// <summary>
        /// 出现时机,0常驻，1随机
        /// </summary>
        public XorInt exist_time_xor;
     /// <summary>
        /// 出现时机,0常驻，1随机
        /// </summary>
        public int exist_time{
            get{
                return exist_time_xor.val;
            }
        }
     /// <summary>
        /// 单抽免费CD
        /// </summary>
        public XorInt one_hour_xor;
     /// <summary>
        /// 单抽免费CD
        /// </summary>
        public int one_hour{
            get{
                return one_hour_xor.val;
            }
        }
     /// <summary>
        /// 十连抽免费CD
        /// </summary>
        public XorInt ten_hour_xor;
     /// <summary>
        /// 十连抽免费CD
        /// </summary>
        public int ten_hour{
            get{
                return ten_hour_xor.val;
            }
        }
     /// <summary>
        /// 单抽铜钱
        /// </summary>
        public XorInt one_cost_coin_xor;
     /// <summary>
        /// 单抽铜钱
        /// </summary>
        public int one_cost_coin{
            get{
                return one_cost_coin_xor.val;
            }
        }
     /// <summary>
        /// 十连抽铜钱
        /// </summary>
        public XorInt ten_cost_coin_xor;
     /// <summary>
        /// 十连抽铜钱
        /// </summary>
        public int ten_cost_coin{
            get{
                return ten_cost_coin_xor.val;
            }
        }
     /// <summary>
        /// 等价招募卷物品ID
        /// </summary>
        public string equal_good_id;
     /// <summary>
        /// 提升招募prop
        /// </summary>
        public string add_player_prop;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictZhaomuZhaomuDropType m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_zhaomu_zhaomu_drop_type.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.say = DictTypeConvert.ParseString(str[fileReader.typeName2Index["say"]]);
            model.hero_icon = DictTypeConvert.ParseString(str[fileReader.typeName2Index["hero_icon"]]);
            model.detail = DictTypeConvert.ParseString(str[fileReader.typeName2Index["detail"]]);
            model.gongshi = DictTypeConvert.ParseString(str[fileReader.typeName2Index["gongshi"]]);
            model.propId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["propId"]]);
            model.one_cost_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["one_cost"]]),fileReader.randomUtil);
            model.ten_cost_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["ten_cost"]]),fileReader.randomUtil);
            model.exist_time_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["exist_time"]]),fileReader.randomUtil);
            model.one_hour_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["one_hour"]]),fileReader.randomUtil);
            model.ten_hour_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["ten_hour"]]),fileReader.randomUtil);
            model.one_cost_coin_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["one_cost_coin"]]),fileReader.randomUtil);
            model.ten_cost_coin_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["ten_cost_coin"]]),fileReader.randomUtil);
            model.equal_good_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["equal_good_id"]]);
            model.add_player_prop = DictTypeConvert.ParseString(str[fileReader.typeName2Index["add_player_prop"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictZhaomuZhaomuDropType Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
