//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictRecharge
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 英雄id
        /// </summary>
        public string id;
     /// <summary>
        /// 平台标识符
        /// </summary>
        public string pingtai_id;
     /// <summary>
        /// 平台
        /// </summary>
        public string channelID;
     /// <summary>
        /// 平台数量
        /// </summary>
        public string pingtai_num;
     /// <summary>
        /// 购买类型
        /// </summary>
        public XorInt recharge_type_xor;
     /// <summary>
        /// 购买类型
        /// </summary>
        public int recharge_type{
            get{
                return recharge_type_xor.val;
            }
        }
     /// <summary>
        /// 参数
        /// </summary>
        public List<string> type_params;
     /// <summary>
        /// 是否有效
        /// </summary>
        public XorInt show_xor;
     /// <summary>
        /// 是否有效
        /// </summary>
        public int show{
            get{
                return show_xor.val;
            }
        }
     /// <summary>
        /// 灵石
        /// </summary>
        public XorInt ruby_xor;
     /// <summary>
        /// 灵石
        /// </summary>
        public int ruby{
            get{
                return ruby_xor.val;
            }
        }
     /// <summary>
        /// 花费RMB
        /// </summary>
        public XorDouble rmb_xor;
     /// <summary>
        /// 花费RMB
        /// </summary>
        public double rmb{
            get{
                return rmb_xor.val;
            }
        }
     /// <summary>
        /// 增加会员值
        /// </summary>
        public XorInt huiyuan_val_xor;
     /// <summary>
        /// 增加会员值
        /// </summary>
        public int huiyuan_val{
            get{
                return huiyuan_val_xor.val;
            }
        }
     /// <summary>
        /// 图标
        /// </summary>
        public string icon;
     /// <summary>
        /// 标题
        /// </summary>
        public string title;
     /// <summary>
        /// 描述
        /// </summary>
        public string desc;
     /// <summary>
        /// 补发描述
        /// </summary>
        public string send_mail_desc;
     /// <summary>
        /// 描述
        /// </summary>
        public string not_first_desc;
     /// <summary>
        /// 补发描述
        /// </summary>
        public string not_first_send_mail_desc;
     /// <summary>
        /// 赠送礼包
        /// </summary>
        public List<string> send_rewards;
     /// <summary>
        /// 非首次赠送礼包
        /// </summary>
        public List<string> not_first_rewards;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<string, Model> m_dict;

    // Get The Dictionary
    public Dictionary<string, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(string id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictRecharge m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_recharge.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<string,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["id"]]);
            model.pingtai_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["pingtai_id"]]);
            model.channelID = DictTypeConvert.ParseString(str[fileReader.typeName2Index["channelID"]]);
            model.pingtai_num = DictTypeConvert.ParseString(str[fileReader.typeName2Index["pingtai_num"]]);
            model.recharge_type_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["recharge_type"]]),fileReader.randomUtil);
            model.type_params = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["type_params"]]);
            model.show_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["show"]]),fileReader.randomUtil);
            model.ruby_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["ruby"]]),fileReader.randomUtil);
            model.rmb_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["rmb"]]),fileReader.randomUtil);
            model.huiyuan_val_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["huiyuan_val"]]),fileReader.randomUtil);
            model.icon = DictTypeConvert.ParseString(str[fileReader.typeName2Index["icon"]]);
            model.title = DictTypeConvert.ParseString(str[fileReader.typeName2Index["title"]]);
            model.desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["desc"]]);
            model.send_mail_desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["send_mail_desc"]]);
            model.not_first_desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["not_first_desc"]]);
            model.not_first_send_mail_desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["not_first_send_mail_desc"]]);
            model.send_rewards = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["send_rewards"]]);
            model.not_first_rewards = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["not_first_rewards"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictRecharge Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
