//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictHeroStarAbility
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 技能id
        /// </summary>
        public string id;
     /// <summary>
        /// 名字
        /// </summary>
        public string name;
     /// <summary>
        /// 英雄ID
        /// </summary>
        public string hero_id;
     /// <summary>
        /// 解锁星级
        /// </summary>
        public XorInt hero_star_xor;
     /// <summary>
        /// 解锁星级
        /// </summary>
        public int hero_star{
            get{
                return hero_star_xor.val;
            }
        }
     /// <summary>
        /// 提高英雄能力
        /// </summary>
        public List<string> advance_heros;
     /// <summary>
        /// 能力
        /// </summary>
        public string abilityId;
     /// <summary>
        /// 能力提升
        /// </summary>
        public string abilityId_lev;
     /// <summary>
        /// 顺序
        /// </summary>
        public XorInt order_xor;
     /// <summary>
        /// 顺序
        /// </summary>
        public int order{
            get{
                return order_xor.val;
            }
        }
     /// <summary>
        /// 文字描述
        /// </summary>
        public string desc;
     /// <summary>
        /// 文字描述
        /// </summary>
        public string new_desc;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<string, Model> m_dict;

    // Get The Dictionary
    public Dictionary<string, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(string id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictHeroStarAbility m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_hero_star_ability.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<string,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["id"]]);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.hero_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["hero_id"]]);
            model.hero_star_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["hero_star"]]),fileReader.randomUtil);
            model.advance_heros = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["advance_heros"]]);
            model.abilityId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["abilityId"]]);
            model.abilityId_lev = DictTypeConvert.ParseString(str[fileReader.typeName2Index["abilityId_lev"]]);
            model.order_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["order"]]),fileReader.randomUtil);
            model.desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["desc"]]);
            model.new_desc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["new_desc"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictHeroStarAbility Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
