//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictPlayerYueliLevel
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// ID
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// ID
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 阅历等级名称
        /// </summary>
        public string name;
     /// <summary>
        /// 品质
        /// </summary>
        public XorInt qulity_xor;
     /// <summary>
        /// 品质
        /// </summary>
        public int qulity{
            get{
                return qulity_xor.val;
            }
        }
     /// <summary>
        /// 属性提升
        /// </summary>
        public string advance_add;
     /// <summary>
        /// 升级阅历
        /// </summary>
        public XorLong upExp_xor;
     /// <summary>
        /// 升级阅历
        /// </summary>
        public long upExp{
            get{
                return upExp_xor.val;
            }
        }
     /// <summary>
        /// 累计阅历
        /// </summary>
        public XorLong leijiExp_xor;
     /// <summary>
        /// 累计阅历
        /// </summary>
        public long leijiExp{
            get{
                return leijiExp_xor.val;
            }
        }
     /// <summary>
        /// 图标
        /// </summary>
        public string spriteName;
     /// <summary>
        /// 进阶任务
        /// </summary>
        public List<string> advance_task;
     /// <summary>
        /// 任务奖励
        /// </summary>
        public string reward_task;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictPlayerYueliLevel m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_player_yueli_level.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.qulity_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["qulity"]]),fileReader.randomUtil);
            model.advance_add = DictTypeConvert.ParseString(str[fileReader.typeName2Index["advance_add"]]);
            model.upExp_xor = new XorLong(DictTypeConvert.ParseLong(str[fileReader.typeName2Index["upExp"]]),fileReader.randomUtil);
            model.leijiExp_xor = new XorLong(DictTypeConvert.ParseLong(str[fileReader.typeName2Index["leijiExp"]]),fileReader.randomUtil);
            model.spriteName = DictTypeConvert.ParseString(str[fileReader.typeName2Index["spriteName"]]);
            model.advance_task = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["advance_task"]]);
            model.reward_task = DictTypeConvert.ParseString(str[fileReader.typeName2Index["reward_task"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictPlayerYueliLevel Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
