//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictRenwuMain
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 任务ID
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 任务ID
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 名称
        /// </summary>
        public string name;
     /// <summary>
        /// 地图
        /// </summary>
        public string map;
     /// <summary>
        /// 任务类型
        /// </summary>
        public string type;
     /// <summary>
        /// 任务类型2
        /// </summary>
        public string sub_type;
     /// <summary>
        /// 等级
        /// </summary>
        public XorInt level_xor;
     /// <summary>
        /// 等级
        /// </summary>
        public int level{
            get{
                return level_xor.val;
            }
        }
     /// <summary>
        /// 任务NPC
        /// </summary>
        public string npc;
     /// <summary>
        /// 任务NPCID
        /// </summary>
        public string npc_id;
     /// <summary>
        /// 流程
        /// </summary>
        public string detail;
     /// <summary>
        /// 奖励
        /// </summary>
        public string reward;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictRenwuMain m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_renwu_main.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.name = DictTypeConvert.ParseString(str[fileReader.typeName2Index["name"]]);
            model.map = DictTypeConvert.ParseString(str[fileReader.typeName2Index["map"]]);
            model.type = DictTypeConvert.ParseString(str[fileReader.typeName2Index["type"]]);
            model.sub_type = DictTypeConvert.ParseString(str[fileReader.typeName2Index["sub_type"]]);
            model.level_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["level"]]),fileReader.randomUtil);
            model.npc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["npc"]]);
            model.npc_id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["npc_id"]]);
            model.detail = DictTypeConvert.ParseString(str[fileReader.typeName2Index["detail"]]);
            model.reward = DictTypeConvert.ParseString(str[fileReader.typeName2Index["reward"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictRenwuMain Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
