//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictHeroSkillEffect
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 技能id
        /// </summary>
        public string id;
     /// <summary>
        /// 缩放
        /// </summary>
        public XorDouble scale_x_xor;
     /// <summary>
        /// 缩放
        /// </summary>
        public double scale_x{
            get{
                return scale_x_xor.val;
            }
        }
     /// <summary>
        /// 缩放
        /// </summary>
        public XorDouble scale_y_xor;
     /// <summary>
        /// 缩放
        /// </summary>
        public double scale_y{
            get{
                return scale_y_xor.val;
            }
        }
     /// <summary>
        /// 缩放
        /// </summary>
        public XorDouble scale_z_xor;
     /// <summary>
        /// 缩放
        /// </summary>
        public double scale_z{
            get{
                return scale_z_xor.val;
            }
        }
     /// <summary>
        /// 偏移
        /// </summary>
        public XorDouble offset_x_xor;
     /// <summary>
        /// 偏移
        /// </summary>
        public double offset_x{
            get{
                return offset_x_xor.val;
            }
        }
     /// <summary>
        /// 偏移
        /// </summary>
        public XorDouble offset_y_xor;
     /// <summary>
        /// 偏移
        /// </summary>
        public double offset_y{
            get{
                return offset_y_xor.val;
            }
        }
     /// <summary>
        /// 偏移
        /// </summary>
        public XorDouble offset_z_xor;
     /// <summary>
        /// 偏移
        /// </summary>
        public double offset_z{
            get{
                return offset_z_xor.val;
            }
        }

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<string, Model> m_dict;

    // Get The Dictionary
    public Dictionary<string, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(string id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictHeroSkillEffect m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_hero_skill_effect.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<string,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id = DictTypeConvert.ParseString(str[fileReader.typeName2Index["id"]]);
            model.scale_x_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["scale_x"]]),fileReader.randomUtil);
            model.scale_y_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["scale_y"]]),fileReader.randomUtil);
            model.scale_z_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["scale_z"]]),fileReader.randomUtil);
            model.offset_x_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["offset_x"]]),fileReader.randomUtil);
            model.offset_y_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["offset_y"]]),fileReader.randomUtil);
            model.offset_z_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["offset_z"]]),fileReader.randomUtil);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictHeroSkillEffect Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
