//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictMenpaiMenpaiZhuanzhiTask
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 主键
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 主键
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 门派ID
        /// </summary>
        public XorInt menpai_id_xor;
     /// <summary>
        /// 门派ID
        /// </summary>
        public int menpai_id{
            get{
                return menpai_id_xor.val;
            }
        }
     /// <summary>
        /// 筛选
        /// </summary>
        public XorInt order_xor;
     /// <summary>
        /// 筛选
        /// </summary>
        public int order{
            get{
                return order_xor.val;
            }
        }
     /// <summary>
        /// 转职名称
        /// </summary>
        public string zhuanzhiName;
     /// <summary>
        /// 转职任务名称
        /// </summary>
        public string taskName;
     /// <summary>
        /// 转职任务说明
        /// </summary>
        public string taskDesc;
     /// <summary>
        /// 前置条件
        /// </summary>
        public List<string> preTaskidd;
     /// <summary>
        /// 转职任务
        /// </summary>
        public string taskGroupId;
     /// <summary>
        /// 转职信赖预览
        /// </summary>
        public string preRewardId;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictMenpaiMenpaiZhuanzhiTask m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_menpai_menpai_zhuanzhi_task.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.menpai_id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["menpai_id"]]),fileReader.randomUtil);
            model.order_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["order"]]),fileReader.randomUtil);
            model.zhuanzhiName = DictTypeConvert.ParseString(str[fileReader.typeName2Index["zhuanzhiName"]]);
            model.taskName = DictTypeConvert.ParseString(str[fileReader.typeName2Index["taskName"]]);
            model.taskDesc = DictTypeConvert.ParseString(str[fileReader.typeName2Index["taskDesc"]]);
            model.preTaskidd = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["preTaskidd"]]);
            model.taskGroupId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["taskGroupId"]]);
            model.preRewardId = DictTypeConvert.ParseString(str[fileReader.typeName2Index["preRewardId"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictMenpaiMenpaiZhuanzhiTask Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
