//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictPlayerFenshenLev
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 主键
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 主键
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 等级
        /// </summary>
        public XorInt level_xor;
     /// <summary>
        /// 等级
        /// </summary>
        public int level{
            get{
                return level_xor.val;
            }
        }
     /// <summary>
        /// 品质(无用)
        /// </summary>
        public XorInt quality_xor;
     /// <summary>
        /// 品质(无用)
        /// </summary>
        public int quality{
            get{
                return quality_xor.val;
            }
        }
     /// <summary>
        /// 升级材料
        /// </summary>
        public List<string> cost;
     /// <summary>
        /// 分身打坐收益
        /// </summary>
        public XorDouble reward_per_xor;
     /// <summary>
        /// 分身打坐收益
        /// </summary>
        public double reward_per{
            get{
                return reward_per_xor.val;
            }
        }
     /// <summary>
        /// 分身碎炼五彩石消耗载数
        /// </summary>
        public XorInt wucai_cost_years_xor;
     /// <summary>
        /// 分身碎炼五彩石消耗载数
        /// </summary>
        public int wucai_cost_years{
            get{
                return wucai_cost_years_xor.val;
            }
        }

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictPlayerFenshenLev m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_player_fenshen_lev.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.level_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["level"]]),fileReader.randomUtil);
            model.quality_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["quality"]]),fileReader.randomUtil);
            model.cost = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["cost"]]);
            model.reward_per_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["reward_per"]]),fileReader.randomUtil);
            model.wucai_cost_years_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["wucai_cost_years"]]),fileReader.randomUtil);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictPlayerFenshenLev Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
